### ISSUE TITLE
Check what keys can decrypt PGP MESSAGE

### ISSUE THREAD

**Issue by DenBond7** [vanitasvitae/pgpainless#183]
I have a question. Please look at the following screenshots

![Selection_805](https://user-images.githubusercontent.com/2863246/133219434-56047dc6-afd8-4f83-8df7-8febd1762b7c.png)

It's true for FlowCrypt for Android that uses Node.js to decrypt a `PGP message`. When I try to decrypt such a message and don't provide passphrases, Node.js realization returns me an error that contains info about keys that have missed passphrases. Looks like this

``` json
{
   "type":"decryptErr",
   "content":"-----BEGIN PGP MESSAGE----- ...-----END PGP MESSAGE-----",
   "decryptErr":{
      "success":false,
      "error":{
         "type":"need_passphrase",
         "message":"Missing pass phrase"
      },
      "longids":{
         "message":[
            "D7A3DEDB65CB1EFB",
            "CCEBCFC9A5417178",
            "4F1458BD22B7BB53"
         ],
         "matching":[
            "45F0A5260A80F238598DD081C669001D0A6DCAC8",
            "3DEBE9F677D5B9BB38E5A244225F8023C20D0957"
         ],
         "chosen":[
            
         ],
         "needPassphrase":[
            "45F0A5260A80F238598DD081C669001D0A6DCAC8",
            "3DEBE9F677D5B9BB38E5A244225F8023C20D0957"
         ]
      },
      "isEncrypted":true
   },
   "complete":true
}
```

`needPassphrase` says me what keys have missed passphrase. **Could we have something similar in `PGPainless`? Could I know for what keys the message was encrypted?**

###########################################

How I can receive `NEED_PASSPHRASE` error with `PGPainless`

```kotlin
override fun getSecretKeyRingProtector(): SecretKeyRingProtector {
    val keyRingProtectionSettings = KeyRingProtectionSettings.secureDefaultSettings()
    val availablePGPSecretKeyRings = getPGPSecretKeyRings()//existed keys
    return PasswordBasedSecretKeyRingProtector(keyRingProtectionSettings) { keyId ->
      for (pgpSecretKeyRing in availablePGPSecretKeyRings) {
        val keyIDs = pgpSecretKeyRing.secretKeys.iterator().asSequence().map { it.keyID }
        if (keyIDs.contains(keyId)) {
          for (secretKey in pgpSecretKeyRing.secretKeys) {
            val openPgpV4Fingerprint = OpenPgpV4Fingerprint(secretKey)
            val fingerprint = openPgpV4Fingerprint.toString()
            val passphrase = getPassphraseByFingerprint(fingerprint)
            if (passphrase == null || passphrase.isEmpty) {
              throw DecryptionException(
                decryptionErrorType = PgpDecrypt.DecryptionErrorType.NEED_PASSPHRASE,
                e = PGPException("flowcrypt: need passphrase"),
                fingerprints = listOf(fingerprint)
              )
            }
            return@PasswordBasedSecretKeyRingProtector passphrase
          }
        }
      }

      return@PasswordBasedSecretKeyRingProtector null
    }
  }
```
Later I use `getSecretKeyRingProtector()` with the following code

```kotlin
fun decryptWithResult(
    srcInputStream: InputStream,
    pgpSecretKeyRingCollection: PGPSecretKeyRingCollection,
    protector: SecretKeyRingProtector //`getSecretKeyRingProtector()`
  ): DecryptionResult {
    srcInputStream.use { srcStream ->
      val destOutputStream = ByteArrayOutputStream()
      destOutputStream.use { outStream ->
        try {
          val decryptionStream = PGPainless.decryptAndOrVerify()
            .onInputStream(srcStream)
            .withOptions(
              ConsumerOptions()
                .addDecryptionKeys(pgpSecretKeyRingCollection, protector)
            )

          decryptionStream.use { it.copyTo(outStream) }
          return DecryptionResult.withDecrypted(
            content = destOutputStream,
            filename = decryptionStream.result.fileName
          )
        } catch (e: Exception) {
          return DecryptionResult.withError(
            processDecryptionException(e)
          )
        }
      }
    }
  }
```

But this approach returns me only the first found issue. Instead, I would like to know info about all keys. In that case, I can propose a user provide a passphrase at least for one of the keys.

@vanitasvitae Please let me know If you need more clarifications.

**Comment by vanitasvitae** [comment]
I would suggest using the `CachingSecretKeyRingProtector` class.
You can pass it a `SecretKeyPassphraseProvider` as callback function which is called for each missing key passphrase.

Eg:
```
    SecretKeyPassphraseProvider callback = new SecretKeyPassphraseProvider() {
            @Nullable
            @Override
            public Passphrase getPassphraseFor(Long keyId) {
                // prompt user for passphrase in UI
                return passphrase;
            }
    };
    CachingSecretKeyRingProtector protector = new CachingSecretKeyRingProtector(callback);
```

Now whenever there is a key for which the passphrase is missing, PGPainless will call the `getPassphraseFor()` method of the callback which you can use to prompt the user to enter the passphrase.
Afterwards the passphrase will be cached in the protector.

Edit: Let me know if this is what you are looking for :)

**Comment by DenBond7** [comment]
unfortunately, it doesn't fit our needs. This approach uses a sequence. And I should provide a passphrase immediately. Otherwise, I will catch an exception(that relates to a single key). To be short, in the Android world it will be a little hard to use that strategy (different threads and so on).

> Could I know for what keys the message was encrypted?

What about that? Can we have any additional info when we try to decrypt a message? or for example check a message for that info.

For example, I have the following

```
-----BEGIN PGP MESSAGE-----
Version: PGPainless

hF4D16Pe22XLHvsSAQdA+cgF8qgAX5lRtuSzCVzwbyEq24srMTdzL/0HWa0sjXgw
E6aJjgjGlcCqHaMssSCAx7v6a1OkONRJmOkUeafNxOy8CNUlPOFhcDWnmKILjuMj
hF4DTxRYvSK3u1MSAQdAs1C904AQanwQRp0eZ/1IINQ39wA+xDo6KTyqLFzHKWYw
NeR9FoAQ1b4T+KtlgQH9UVh1jw1U++tMuwVOHYqCuomJ1oMfvMcO9CO3wC4tvi5K
0sAYAcFYdIyg3ILeNhpOhWFDeXdSgID5KaFMsm45eRl9ZdvQNz/VwqOwMhD8acbO
IscIBwqgfxaS0BoNlcj5ao0T0wrTb6fJvwT/YZ5QTXfBzxzHIB1nuFgJqnrpsHom
18zRc1igiWm5nPhdwGTmfeH586HQZwKubXrNvEKE41Rl3Wn7PjUAgkwkV9KOyW3W
tilaJQHxPFI7lTUtMzFffVs3Qe0Gz+03x+7MGnTSDO1Bg5/h4Tttc6V7rPViI+rG
kWGg1Aw3Ev6T+bBTfk20oL77zbrscUKlTezO
=gcMh
-----END PGP MESSAGE-----
```

Can we check for what keys this message was encrypted? It will help me.

Something similar to this one

![Selection_806](https://user-images.githubusercontent.com/2863246/133241720-8d31e856-00b6-4ee0-8c2f-245304d20d36.png)

**Comment by vanitasvitae** [comment]
Yeah that should be doable.
Basically a method which parses the message "header" to extract recipients and signers.

**Comment by vanitasvitae** [comment]
I added `MessageInspector` which can be used to determine recipient key-ids and whether a message is passphrase protected.

**Comment by DenBond7** [comment]
> I added `MessageInspector` which can be used to determine recipient key-ids and whether a message is passphrase protected.

Great! Thank you. It will be very helpful.

**Comment by DenBond7** [comment]
But I've found another issue. I propose to discuss the following code

```kotlin
fun decryptWithResult(
    srcInputStream: InputStream,
    pgpSecretKeyRingCollection: PGPSecretKeyRingCollection,
    protector: SecretKeyRingProtector
  ): DecryptionResult {
    srcInputStream.use { srcStream ->
      val destOutputStream = ByteArrayOutputStream()
      destOutputStream.use { outStream ->
        try {
          val decryptionStream = PGPainless.decryptAndOrVerify()
            .onInputStream(srcStream)
            .withOptions(
              ConsumerOptions()
                .addDecryptionKeys(pgpSecretKeyRingCollection, protector)
            )

          decryptionStream.use { it.copyTo(outStream) }
          return DecryptionResult.withDecrypted(
            content = destOutputStream,
            filename = decryptionStream.result.fileName
          )
        } catch (e: Exception) {
          return DecryptionResult.withError(
            processDecryptionException(e)
          )
        }
      }
    }
  }
```
where 

- `srcInputStream: InputStream` - our `-----BEGIN PGP MESSAGE-----...-----END PGP MESSAGE-----`
- `pgpSecretKeyRingCollection: PGPSecretKeyRingCollection` - contains private keys that can be used to decrypt a message from `srcInputStream`(let's imagine it contains 2 keys: `A` and `B`)
- `protector: SecretKeyRingProtector` - handles fetching passphrase for `pgpSecretKeyRingCollection`(let's imagine it contains just one passphrase for `B`)

### expected results

If we try to decrypt a message that was encrypted for 2 keys(`A` and `B`) and just pass only one passphrase for `B` we should be able to decrypt that message. Because for at least one suitable key we have a passphrase

### actual results

Due to a logic **one by one** `PGPainless` takes the first key from the ring collection(`A` in our case), asks `protector` to provide a passphrase for `A`, and throws an exception. But we have key `B` and a passphrase for this key.

**Comment by DenBond7** [comment]
I've opened a new issue. The current issue can be closed because you've added the requested changes.
