### ISSUE TITLE
Improve decrypt with PGPSecretKeyRingCollection

### ISSUE THREAD

**Issue by DenBond7** [vanitasvitae/pgpainless#186]
But I've found another issue. I propose to discuss the following code

```kotlin
fun decryptWithResult(
    srcInputStream: InputStream,
    pgpSecretKeyRingCollection: PGPSecretKeyRingCollection,
    protector: SecretKeyRingProtector
  ): DecryptionResult {
    srcInputStream.use { srcStream ->
      val destOutputStream = ByteArrayOutputStream()
      destOutputStream.use { outStream ->
        try {
          val decryptionStream = PGPainless.decryptAndOrVerify()
            .onInputStream(srcStream)
            .withOptions(
              ConsumerOptions()
                .addDecryptionKeys(pgpSecretKeyRingCollection, protector)
            )

          decryptionStream.use { it.copyTo(outStream) }
          return DecryptionResult.withDecrypted(
            content = destOutputStream,
            filename = decryptionStream.result.fileName
          )
        } catch (e: Exception) {
          return DecryptionResult.withError(
            processDecryptionException(e)
          )
        }
      }
    }
  }
```
where 

- `srcInputStream: InputStream` - our `-----BEGIN PGP MESSAGE-----...-----END PGP MESSAGE-----`
- `pgpSecretKeyRingCollection: PGPSecretKeyRingCollection` - contains private keys that can be used to decrypt a message from `srcInputStream`(let's imagine it contains 2 keys: `A` and `B`)
- `protector: SecretKeyRingProtector` - handles fetching passphrase for `pgpSecretKeyRingCollection`(let's imagine it contains just one passphrase for `B`)

### expected results

If we try to decrypt a message that was encrypted for 2 keys(`A` and `B`) and just pass only one passphrase for `B` we should be able to decrypt that message. Because for at least one suitable key we have a passphrase

### actual results

Due to a logic **one by one** `PGPainless` takes the first key from the ring collection(`A` in our case), asks `protector` to provide a passphrase for `A`, and throws an exception. But we have key `B` and a passphrase for this key.

_Originally posted by @DenBond7 in https://github.com/pgpainless/pgpainless/issues/183#issuecomment-919771807_

**Comment by vanitasvitae** [comment]
I changed the decryption logic, such that PGPainless will
* first try to decrypt any password based encrypted session keys
* then try any public key encrypted session keys where the decryption key has a passphrase available
* then try any public key encrypted sesison keys where the passphrase is missing which causes callbacks to fire

This should also work with wildcard encrypted data.

**Comment by DenBond7** [comment]
Thank you! I've checked - your changes fix an issue.

**Comment by DenBond7** [comment]
One more question. Do you have a plan to post a new update(0.2.13)?

**Comment by vanitasvitae** [comment]
I'm doing that right now :P

**Comment by vanitasvitae** [comment]
Done.
