### ISSUE TITLE
Add an option that is similar to gpg --ignore-mdc-error

### ISSUE THREAD

**Issue by DenBond7** [vanitasvitae/pgpainless#190]
It would be nice to have an option like `ignoreMdc: true` to be able to decrypt messages without MDC

For example, instead of 

```java
if (!encryptedData.isIntegrityProtected()) {
                throw new MessageNotIntegrityProtectedException();
}
```
have the following

```java
if (!options.ignoreMdc && !encryptedData.isIntegrityProtected()) {
                throw new MessageNotIntegrityProtectedException();
}
```

**Comment by tomholub** [comment]
We'd use this after we already know that there is an MDC problem and warned the user about the risk, and the user wants to view the message contents anyway. Then we'd retry decryption of that message with the above flag.

**Comment by vanitasvitae** [comment]
I'm a bit hesitant to add features that degrade security, but maybe it makes sense to add this as a config option.

I will tackle this tomorrow.

**Comment by tomholub** [comment]
I suppose the feature is not _strictly_ required on Android. I understand & share your hesitation. I may be ok to drop it.

**Comment by vanitasvitae** [comment]
I added `ConsumerOptions.setIgnoreMDCErrors(boolean)` which can be used to ignore certain MDC-related issues (see [javadoc](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/main/java/org/pgpainless/decryption_verification/ConsumerOptions.java#L270-L293) for more detail).
