### ISSUE TITLE
Need a way to mark/unmark UID as primary

### ISSUE THREAD

**Issue by IvanPizhenko** [vanitasvitae/pgpainless#216]
Hi Paul, we need a convenience methods in the `SecretKeyRingEditor` to do the following:
- Mark certain UID as primary (should only perform actual action if a given UID is not marked primary).
- Unmark certain UID as primary (should only perform actual action if a given UID is marked primary).

We have recently found that this is flag based and not order based. See https://datatracker.ietf.org/doc/html/rfc4880#section-5.2.3.19

@Jerbell @rrrooommmaaa @tomholub FYI

**Comment by vanitasvitae** [comment]
The new signature builder API (that is still WIP, but close to be ready for merging) will enable you to do that.
Can you point me to other implementations APIs for doing this? I'd like to know whether or not I'm on the right track in terms of API design :D

**Comment by IvanPizhenko** [comment]
Hi Paul, sorry, but I did not check how to do it with BC and unlikely will do in the nearest time. So it is now up to you to figure out how to do that properly. It should be like adding another self-signature stating that certain UID is primary. Then, in case of multiple such signatures, primary UID should be resolved to the latest valid signature (standard recommends to do so, but only recommends). I did not check how BC and PGPainless do this. Will this work?

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa has discovered following:
As there may be several userids marked as primary, they should be ordered somehow more or less deterministically. This is not strictly documented by RFC4880.
OpenPGP.js, for example orders userids this way: revoked ASC, isPrimaryUserID DESC, created DESC.
Those 3 are attributes of a signature packet found by getLatestValidSignature() for this UserID.

**Comment by IvanPizhenko** [comment]
Currently, if we just set new uid that we need to be primary, to a first position, while retaining old uid, it just doesn't work - primary uid still the old one, and I assume it is based on the fact that primary uid is flag-based, not position based. we need a way to make first uid primary and remove primary mark for all other uids. Whatever chain of signatures PGPainless would construct, must be compatible with OpenPGP.js, so that we get same results in the both in terms of which UID is primary.

**Comment by vanitasvitae** [comment]
I think it might be a good idea to resolve the situation where there are multiple primary-marked user-ids by sorting them by signature creation date and accepting the most recent one as being primary.

If we change the primary user-id on a key lets say from "A" to "B", I would create new signatures for both "A" and "B", where "A" would not carry a primary user-id flag while "B" would.

I will try to get the signature builder finished as quickly as possible, so that we can add some convenience methods on top.

**Comment by vanitasvitae** [comment]
This can now be implemented as follows:
```
        PGPSecretKeyRing secretKeys = ... // key with primary user-id = "Alice"

        KeyRingInfo info = PGPainless.inspectKeyRing(secretKeys);
        assertEquals("Alice", info.getPrimaryUserId());

        // mark user-id "Bob" as primary, unmark "Alice"
        secretKeys = PGPainless.modifyKeyRing(secretKeys)
                .addUserId("Bob",
                        new SelfSignatureSubpackets.Callback() {
                            @Override
                            public void modifyHashedSubpackets(SelfSignatureSubpackets hashedSubpackets) {
                                hashedSubpackets.setPrimaryUserId(); // mark new user-id as primary
                            }
                        },
                        protector)
                .addUserId("Alice", protector) // overwrite "Alice" as non-primary user-id
                .done();

        info = PGPainless.inspectKeyRing(secretKeys);
        assertEquals("Bob", info.getPrimaryUserId());
```

**Comment by vanitasvitae** [comment]
Please try the new release (there have been some refactoring, so it might take some work to apply changes) and let me know what you think :)

**Comment by IvanPizhenko** [comment]
Thank you, will try

**Comment by IvanPizhenko** [comment]
@vanitasvitae I have a code:
```kotlin
    val generate = generateKeyRing()
      .setPrimaryKey(KeySpec.getBuilder(keypairAlgo.signingKeyType, KeyFlag.SIGN_DATA, KeyFlag.CERTIFY_OTHER))
      .addSubkey(KeySpec.getBuilder(keypairAlgo.encryptionKeyType, KeyFlag.ENCRYPT_COMMS, KeyFlag.ENCRYPT_STORAGE))
```
With pgpainless-1.0.0-rc4 it is no longer compiles. Missing method `setPrimaryKey`. What should I do instead?

**UPDATE**: looks like I need to use `buildKeyRing()` now.

**Comment by IvanPizhenko** [comment]
@vanitasvitae I have another code:
```kotlin
            val editor = PGPainless.modifyKeyRing(secretKeyRing)
            ....
            val selectionStrategy = SelectUserId.or(
              SelectUserId.containsEmailAddress(uid.email),
              SelectUserId.exactMatch(uid.email)
            )
            editor.deleteUserId(selectionStrategy, unprotectedProtector)
```
As you recommended, I've tried to change `deleteUserId()` to `revokeUserId()`, however there is no overloaded method `revokeUserId()` which takes selection strategy as parameter. Please add such one.
Also as I remember, you promised you will add some temporary helper method which will emulate current `deleteUserId()` for us. Where is it? I'd suggest to leave `deleteUserid()` in place, but mark it deprecated and remove only when we signal you that we have patched our code to work with `revokeUserId()`.

**Comment by vanitasvitae** [comment]
There are these methods in [KeyRingUtils](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/main/java/org/pgpainless/key/util/KeyRingUtils.java#L161-L205) which can be used to delete user-ids.

**Comment by IvanPizhenko** [comment]
@vanitasvitae Can you please put this:
```java
.addUserId("Bob",
                        new SelfSignatureSubpackets.Callback() {
                            @Override
                            public void modifyHashedSubpackets(SelfSignatureSubpackets hashedSubpackets) {
                                hashedSubpackets.setPrimaryUserId(); // mark new user-id as primary
                            }
                        },
                        protector)
```
into new method `addPrimaryUserId()` which takes only userId and protector?

**Comment by IvanPizhenko** [comment]
@vanitasvitae Also another question - assume you have a key and a list of user ids. Some user of user ids on the list are already present on the key and some not. How would you do the following thing with PGPainless: transform a key so that list of its effective user ids would be equal to the given list of user ids? Will the following work:
1. Add user ids that are not yet on the key
2. Revoke user ids that are no longer on the key?

**Comment by vanitasvitae** [comment]
I'd do something like
```
KeyRingInfo info = PGPainless.inspectKeyRing(keys);
List<String> currentIds = info.getValidUserIds(); // contains only currently valid identities, not expired or revoked identities

List<String> missingIds = new ArrayList<>(expectedIds);
missingIds.removeAll(currentIds);
List<String> removalIds = new ArrayList<>(currentIds);
removalIds.removeAll(expectedIds);

SecretKeyRingEditorInterface editor = PGPainless.modifyKeyRing(secretKeys);
for (String userId : missingIds) {
     editor.addUserId(userId, ...);
}
for (String userId : removalIds) {
    editor.revokeUserId(userId, ...); // provide a "soft" revocation reason to allow recertification
}
keys = editor.done();
```

**Comment by IvanPizhenko** [comment]
@vanitasvitae That's good idea.
Can you please add the above into `SecretKeyRingEditor` as `setUserIds()`?
Also see above request for `addPrimaryUserId()`.

**Comment by vanitasvitae** [comment]
I hope it is okay for you if I defer addijg this feature for about two weeks. I try to keep the delta to 1.0.0-rc5 as small as possible in order to make life easier for the cure53 team.

**Comment by tomholub** [comment]
PGPainless is currently under security review, so Paul's trying to minimize changes while security review is undergoing. So there will be a few weeks "feature freeze" to focus on security of PGPainless.

**Comment by IvanPizhenko** [comment]
ok

**Comment by IvanPizhenko** [comment]
@vanitasvitae which one should I use for this: "provide a "soft" revocation reason to allow recertification"?
```kotlin
        NO_REASON((byte) 0),
        KEY_SUPERSEDED((byte) 1),
        KEY_COMPROMISED((byte) 2),
        KEY_RETIRED((byte) 3),
        USER_ID_NO_LONGER_VALID((byte) 32),
```

**Comment by vanitasvitae** [comment]
KEY_SUPERSEDED, KEY_RETIRED are soft. The others (including NO_REASON) are hard as they indicate an incident.

**Comment by IvanPizhenko** [comment]
ok, and which one of these two (in your opinion) fits better to this situation and why? I have used KEY_RETIRED for now.

**Comment by IvanPizhenko** [comment]
I think I've got an answer from exception:
```
  Caused by: java.lang.IllegalArgumentException: Reason 3 - KEY_RETIRED can only be used for key revocations, not to revoke certificates.
```

**Comment by IvanPizhenko** [comment]
But just to check - am I doing correct thing at all?
```kotlin
          val revocationAttributes = RevocationAttributes.createCertificateRevocation()
            .withReason(RevocationAttributes.Reason.KEY_SUPERSEDED)
            .withDescription("")
          editor.revokeUserIds(
            selectionStrategy,
            unprotectedProtector,
            object : RevocationSignatureSubpackets.Callback {
              override fun modifyHashedSubpackets(hashedSubpackets: RevocationSignatureSubpackets?) {
                hashedSubpackets?.setRevocationReason(revocationAttributes)
              }
            }
          )
```

**Comment by IvanPizhenko** [comment]
Hmm, looks like I need to do "key revocation", because these two "soft" types fall into this category.

**Comment by vanitasvitae** [comment]
Ah I just noticed, for user-ids you want to use `USER_ID_NO_LONGER_VALID` which is soft and intended for user-ids. Right now your code will throw an exception since you are trying to use a key-revocation reason for a user-id certification revocation (sorry for my wrong recommendation :P)

You do not need to provide a signature callback in this case, as PGPainless will set the revocation reason for you.

**Comment by vanitasvitae** [comment]
I was wrong again (the Kotlin syntax confused me :D). Sorry for that. Your attempt is actually mostly correct in that you need to provide a revocation reason.
This code should be correct to softly revoke user-ids that match a SelectUserId filter:
```
          val revocationAttributes = RevocationAttributes.createCertificateRevocation()
            .withReason(RevocationAttributes.Reason.USER_ID_NO_LONGER_VALID)
            .withDescription("")
          editor.revokeUserIds(
            selectionStrategy,
            unprotectedProtector,
            object : RevocationSignatureSubpackets.Callback {
              override fun modifyHashedSubpackets(hashedSubpackets: RevocationSignatureSubpackets?) {
                hashedSubpackets?.setRevocationReason(revocationAttributes)
              }
            }
          )
```

**Comment by IvanPizhenko** [comment]
Thank you, restored back my previous code with change to `USER_ID_NO_LONGER_VALID` :))

**Comment by vanitasvitae** [comment]
I decided to do a last release before the audit starts, so I added `addPrimaryUserId()` methods to the `SecretKeyRingEditor`.
I have however not yet implemented a `setUserIds(List)` method, as I'm not yet sure, whats the best way of doing this generically.

**Comment by vanitasvitae** [comment]
A new release will be published sometime before monday.

**Comment by IvanPizhenko** [comment]
Thank you!

**Comment by IvanPizhenko** [comment]
@vanitasvitae such approach works, but then I have another issue:
```kotlin
  private fun doUpdateKeyExpiration(
    secretKeyRing: PGPSecretKeyRing,
    expiration: Instant?,
    protector: SecretKeyRingProtector
  ): PGPSecretKeyRing {
    val parsed = parse(secretKeyRing)
    val subkeyIds = parsed.allIds.filter { it != parsed.id }.map { OpenPgpV4Fingerprint(it) }
    val date = if (expiration == null) null else Date.from(expiration)
    val editor = PGPainless.modifyKeyRing(secretKeyRing).setExpirationDate(date, protector)
    subkeyIds.forEach { editor.setExpirationDate(it, date, protector) }
    return editor.done()
  }
```
After running this on the key with modified users (added new primary user), primary user changes back to the old one.
Sample key: 
[keypair-950EED2D-prv.txt](https://github.com/pgpainless/pgpainless/files/7612644/keypair-950EED2D-prv.txt)
Am I doing something wrong here?

**Comment by vanitasvitae** [comment]
I think I know why this happens. This is a prime example of what complexities one encounters with the OpenPGP spec :D

PGPainless current logic for modifying the expiration date is to re-create the last signature on that datum with a modified expiration date.

Lets say that originally you had user-id A as primary user-id and then marked B as primary. Now B is recognized as the primary user-id since both A and B are marked as such, but B has the newer signature.
Now, if you change the expiration date, the signatures are re-created, which can result in A getting a signature newer than B, resulting in A now being recognized as primary once again.

I'll have to rethink how to deal with this. In the mean time, you could consider "packing" modifications on the key into "transactions", such that instead of creating several signatures, only one signature per datum is sufficient.

You could for example let your user make their desired changes in the UI and then resolve how to make the changes on the key as a single (or maybe some few) signatures.

Lets say the user wants to mark B as primary and set an expiration date of 3y. You could implement this via `addUserId("A", ...)` and pass a subpacket callback which marks the user-id as primary + set an expiration date.

I hope you get the idea and why this is rather complex and can get messy :D

**Comment by IvanPizhenko** [comment]
@vanitasvitae So I suggest to add one more parameter to `addPrimaryUserId()` - `@Nullable KeyExpirationTime primaryKeyExpirationTime`.
Here is what I have implemented as extension method now:
```kotlin
fun SecretKeyRingEditorInterface.addPrimaryUserId(
  userId: String,
  primaryKeyExpirationTime: KeyExpirationTime?,
  secretKeyRingProtector: SecretKeyRingProtector
): SecretKeyRingEditorInterface = addUserId(
  userId,
  object : SelfSignatureSubpackets.Callback {
    override fun modifyHashedSubpackets(hashedSubpackets: SelfSignatureSubpackets?) {
      hashedSubpackets?.setPrimaryUserId()
      hashedSubpackets?.setKeyExpirationTime(primaryKeyExpirationTime)
    }
  },
  secretKeyRingProtector
)
```

**Comment by IvanPizhenko** [comment]
@vanitasvitae please also make public this one: `SignatureSubpacketGeneratorUtil.getKeyLifetimeInSeconds()`

**Comment by vanitasvitae** [comment]
> @vanitasvitae please also make public this one: SignatureSubpacketGeneratorUtil.getKeyLifetimeInSeconds()

I'll make it public and move it to `SignatureSubpacketsUtil` as that's a more appropriate place for it. :+1:

**Comment by vanitasvitae** [comment]
> Here is what I have implemented as extension method now:

That code looks good. Just make sure to use the right type of expiration time to achieve what you want to do. KeyExpirationTime packets expire the whole key, while "normal" expiration time subpackets make the user-id signature expire and can therefore expire the user-id only.

Sometimes I'm jealous of Kotlin and its extension fuctions ;D

**Comment by IvanPizhenko** [comment]
I didn't like Kotlin in the beginning. But after Typescript Kotlin seems so nice. And extension functions are cool stuff. I believe the idea might have came from C# and Groovy. Btw, don't you plan PGPainless for .NET?

**Comment by vanitasvitae** [comment]
FTR: I just released 1.0.0-rc6 with some of the requested changes. Now its feature freeze until in 2 weeks :)

I'm not familiar with .NET, and also not a windows person, so not planned :)

**Comment by IvanPizhenko** [comment]
.NET now is not "Windows only". For example, Red Hat regularly promotes Linux containers with .NET 5 and .NET 6.

**Comment by IvanPizhenko** [comment]
> Now its feature freeze until in 2 weeks :)

So I will keep writing extension methods... :)

**Comment by vanitasvitae** [comment]
> .NET now is not "Windows only". For example, Red Hat regularly promotes Linux containers with .NET 5 and .NET 6.

Interesting, I did not know that.

**Comment by IvanPizhenko** [comment]
So I am really keep writing them :))

@vanitasvitae, so here is my "version 2" of updating expiration date/time on the key.

```kotlin
fun PGPSecretKeyRing.setExpiration(expiration: Instant?, protector: SecretKeyRingProtector): PGPSecretKeyRing {
  val info = PGPainless.inspectKeyRing(this)
  val primaryUserId = info.primaryUserId
  val publicKey = this.publicKey
  val fingerprint = publicKey.fingerprint
  val subkeyIds = this.publicKeys.asSequence()
    .filter { !it.fingerprint.contentEquals(fingerprint) }
    .map { OpenPgpV4Fingerprint(it) }
  val expirationDate = if (expiration == null) null else Date.from(expiration)
  val editor = PGPainless.modifyKeyRing(this)
  subkeyIds.forEach { editor.setExpirationDate(it, expirationDate, protector) }
  if (primaryUserId != null) {
    val keyExpirationTime = if (expirationDate != null) {
      KeyExpirationTime(false, (expirationDate.time - publicKey.creationTime.time) / 1000L)
    } else {
      null
    }
    editor.addPrimaryUserId(primaryUserId, keyExpirationTime, protector)
  }
  return editor.done()
}
```

Then I am doing following test:
Step 1
- Load some expired key
- Update expiration to "now"
- Check result

This one succeeds.

Step 2
- Update resulting key from the Step 1 to expiration "now" + 1 day
- Check result

Step 2 fails, expiration does not change.

What am I doing wrong here?

**Comment by vanitasvitae** [comment]
Signature creation time has a resolution of 1 second.
Maybe your test is too fast, so PGPainless is not detecting the correct signature as most recent?
Try adding a delay of 1+ second between step one and two.

**Comment by IvanPizhenko** [comment]
Thank you, that has worked.

**Comment by IvanPizhenko** [comment]
@vanitasvitae Now I've found another issue with the same code, i.e. listed above `PGPSecretKeyRing.setExpiration()`: I take key with some expiration and trying to set it not expiring. As result the key still has expiration.

**Comment by IvanPizhenko** [comment]
@vanitasvitae FYI about .NET https://developers.redhat.com/articles/2021/11/15/net-60-now-available-rhel-and-openshift

**Comment by IvanPizhenko** [comment]
@vanitasvitae So any ideas why setting no expiration doesn't work?

**Comment by vanitasvitae** [comment]
There is more than one way to set expiration. You can set:
* expiration on user-id signatures which only expire the user-id
* expiration on the primary userid sig. The primary expiration overweighs non-primary user-ids
* expiration on subkey binding signatures. This only expires subkeys at some point
* expiration on a direct-key signature. This expiration expires the whole key ring

Can you provide a JUnit test which fails your expectations? That would be easiest for me to find and rectify the issue.

**Comment by IvanPizhenko** [comment]
Sample unit test:
```kotlin
  fun testSetNoExpiration() {
    val keyPair = readKeypairResource("950EED2D")
    val keyRing = PGPainless.readKeyRing().secretKeyRing(keyPair.prv.armored)
    assertThat(keyRing.publicKey.validSeconds).isGreaterThan(0L)
    // calling extension method listed above
    val updatedKeyRing = keyRing.setExpiration(null, UnprotectedKeysProtector())
    assertThat(updatedKeyRing.publicKey.validSeconds).isEqualTo(0L) // <<< FAILS
  }
```

**Comment by IvanPizhenko** [comment]
@vanitasvitae Any chances to have this resolved soon? I'm blocked with it.

**Comment by vanitasvitae** [comment]
I will give this priority now :+1:

**Comment by vanitasvitae** [comment]
Why are you setting an expiration date for each subkey? It should be sufficient to only set an expiration date for the primary key, as subkeys "inherit" its expiration.

This method
```
    SecretKeyRingEditorInterface setExpirationDate(
            @Nullable Date expiration,
            @Nonnull SecretKeyRingProtector secretKeyRingProtector)
            throws PGPException;
```
sets the expiration date for each user-id on the primary key. That means that all subkeys will be unusable as well once the user-ids expire.

Setting subkey expiration dates is only necessary if you want to explicitly expire a subkey independently from the primary key or other subkeys.

**Comment by vanitasvitae** [comment]
However, I will see if I can make some changes to the expiration date logic, since the current implementation does not take DirectKeySignatures into consideration. I will also need to do some research into how exactly expiration dates from different signature types are expected to be resolved.

PGPainless' signature verification implementation already matches the expectations of the [test suite](https://tests.sequoia-pgp.org/#Certificate_expiration), but the user-facing API for modifying expiration dates is on a different page.

**Comment by IvanPizhenko** [comment]
@tomholub Do you remember something about why it was done this way?

**Comment by IvanPizhenko** [comment]
> Why are you setting an expiration date for each subkey? It should be sufficient to only set an expiration date for the primary key, as subkeys "inherit" its expiration.
> 
> This method
> 
> ```
>     SecretKeyRingEditorInterface setExpirationDate(
>             @Nullable Date expiration,
>             @Nonnull SecretKeyRingProtector secretKeyRingProtector)
>             throws PGPException;
> ```
> 
> sets the expiration date for each user-id on the primary key. That means that all subkeys will be unusable as well once the user-ids expire.
> 
> Setting subkey expiration dates is only necessary if you want to explicitly expire a subkey independently from the primary key or other subkeys.

@tomholub Do you remember something about why it was done this way? i.e. Why are we setting an expiration date for each subkey?

**Comment by tomholub** [comment]
All of these decisions should be done in PGPainless, I think. I have a more important question: why were we doing anything in PGP at this level of detail at all? Either, some functionality was missing in PGPainless at the time, or the interface that PGPainless exposes allows us a little too much decision making, and the interface should be dumbed down.

**Comment by IvanPizhenko** [comment]
It was done before because PGPainless was missing this functionality, and now it didn't work as expected and I was trying to fix it (especially after it has been said that there is feature freeze for 2 weeks due to security review). I agree that normally we need that all to be done completely inside PGPainless.

**Comment by IvanPizhenko** [comment]
@vanitasvitae So I need you to ensure that basically following things can be done easily with PGPainless and work correctly:
1. Take a key with expiration, set expiration to an earlier or later date, check result.
2. Take a key without expiration, set expiration to some date, check result.
3. Take a key with expiration, remove expiration, check result.
4. Items 1-3 above, but before changing expiration, primary user ID is changed. Clarification: changing primary user ID is a separate step.

**Comment by tomholub** [comment]
> Items 1-3 above, but before changing expiration, primary user ID is changed.

Can't this be a separate step, simply "change primary user id" ? Is it related to the other 3?

**Comment by IvanPizhenko** [comment]
> > Items 1-3 above, but before changing expiration, primary user ID is changed.
> 
> Can't this be a separate step, simply "change primary user id" ? Is it related to the other 3?

Yes, change primary user ID is a separate step. 
Assume a scenario - you change primary user id on a key. A year later you extend expiration. No other changes to key during this year. But key is in the state after changing user ID. I specifically mention this scenario because I've found it didn't work properly. After setting expiration primary user id was restored to the old one, which is pretty unexpected, right?

**Comment by tomholub** [comment]
I see. Yes - combinations of these should also be supported over time.

@vanitasvitae does this kind of functionality make sense for PGPainless (after the audit?)

**Comment by vanitasvitae** [comment]
I definitely intend for PGPainless to support this.

**Comment by tomholub** [comment]
@IvanPizhenko let's wait with this until we can fully utilize PGPainless functionality, then update our code to use simple PGPainless methods.

@vanitasvitae is there any issue on PGPainless that tracks this? If no, please open one. Thanks 👍

**Comment by vanitasvitae** [comment]
I just opened #225
