### ISSUE TITLE
'usableForEncryption' method for keys

### ISSUE THREAD

**Issue by DenBond7** [vanitasvitae/pgpainless#223]
We've started to receive reports from our users about **"Key has no suitable encryption subkeys."** issue.

It happens when we are trying to encrypt some content using some pub keys.

```java
public EncryptionOptions addRecipient(PGPPublicKeyRing key, EncryptionKeySelector encryptionKeySelectionStrategy) {
        KeyRingInfo info = new KeyRingInfo(key, new Date());
        Date primaryKeyExpiration = info.getPrimaryKeyExpirationDate();
        if (primaryKeyExpiration != null && primaryKeyExpiration.before(new Date())) {
            throw new IllegalArgumentException("Provided key " + OpenPgpFingerprint.of(key) + " is expired: " + primaryKeyExpiration);
        }
        List<PGPPublicKey> encryptionSubkeys = encryptionKeySelectionStrategy
                .selectEncryptionSubkeys(info.getEncryptionSubkeys(purpose));
        if (encryptionSubkeys.isEmpty()) {
            throw new IllegalArgumentException("Key has no suitable encryption subkeys.");
        }

        for (PGPPublicKey encryptionSubkey : encryptionSubkeys) {
            SubkeyIdentifier keyId = new SubkeyIdentifier(key, encryptionSubkey.getKeyID());
            keyRingInfo.put(keyId, info);
            keyViews.put(keyId, new KeyAccessor.ViaKeyId(info, keyId));
            addRecipientKey(key, encryptionSubkey);
        }

        return this;
    }
```

It seems we allow to import keys that can't be used for encryption.

Does `PGPanless` have predefined code to check if a key can be used for encryption?

1. not revoked 
2. not expired
3. having primary uid
4. having appropriate subkeys
5. ... (maybe something more?)

**Comment by vanitasvitae** [comment]
There are no such checks inside of pgpainless. You can of course check that `PGPainless.inspectKeyRing(pubKeys).getEncryptionSubkeys()` is not empty before storing the key in your database.

**Comment by vanitasvitae** [comment]
I decided to add `KeyRingInfo.isUsableForEncryption()`, as well as `KeyRingInfo.isUsableForEncryption(EncryptionPurpose)`.
