### ISSUE TITLE
On the Topic of Expiration

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/pgpainless#225]
PGPainless aims to provide the user with tools to modify the validity period of keys and user-ids.
Right now however, PGPainless' API does not fully function as expected.

In particular, there are unexpected issues happening when the user changes the primary user-id of a key and later changes the expiration date of the primary key.
The reason for this is that OpenPGP technically allows multiple user-ids to be marked as primary. PGPainless simply picks that one with with latest signature creation date on it.
Therefore, when renewing a signature in order to reissue the expiration date, the old primary user-id is suddenly the most recently modified one and therefore becomes active again.

There are multiple ways of solving this issue:
* when marking user-id B as active, search for all former primary user-ids and create new signatures for them, marking them as non-primary. That way there is only one user-id marked primary at any point in time. However, instead of one signature, we potentially issue multiple one. This is the "prevent the issue from happening but with increased cost"-way to approach the problem.
* when reissuing signatures (e.g. when changing expiration dates) check what the current primary user-id of the key is and unset the primary user-id flag in the reissued signature if it targets a user-id different from the current primary user id. This approach only needs a single signature to be issued at a time. This is the "fix the issue after the fact"-way of tackling the issue.

I tend to go with the first way, since the second approach would need to be implemented in any other use-case that involves signature reissuing and is therefore error-prone.

# Changes to the API
The Sequoia Interoperability Test Suite shows that unfortunately there is no consensus for how to treat some of the many ways signatures with expiration information can be arranged:
![Screenshot 2021-12-07 at 12-39-35 OpenPGP interoperability test suite](https://user-images.githubusercontent.com/7854206/145024362-0ff9c5b6-07c4-448f-b884-99811b2d6aa5.png)

This chart does not even contain separate subkey expiration dates.
Note specifically the white area in the bottom mid section where implementation behavior differs drastically.
So when it comes to re-designing the API for setting expiration dates, I propose to avoid creating such situations from the white area, hence we should avoid setting direct-key-signatures on the primary key. Of course, PGPainless will still continue to evaluate those when processing signature validity.

Requirements for the expiration API are:
* one method for changing the expiration date of the key in its entirety. This method should change the expiration date on the primary user-id.
* one method for changing the expiration date of a specific user-id.
* one method to change the expiration date of a subkey.

One potential edge case are keys without user-ids. These keys do carry a direct-key signature, hence unfortunately we cannot fully ignore the white area from the chart above.

Lets say we have a key without user-ids. Now we change the expiration date, which must re-issue the direct-key signature.
Then we add a primary user-id and set another expiration date. Now how do we expire the key now? Do we re-issue both the direct-key and the primary user-id sig?

So probably a sane solution would look like this:
```
setExpirationDate(date, protector) {
    if (hasDirectKeySig) {
        reissueDirectKeySig(date)
    } 
    if (hasPrimaryUserId) {
        reissuePrimaryUserId(userId, date)
    } 
    if (hasDuplicatePrimaryUserIds) {
        reissueNonPrimaryUserIdsForDuplicates()
    }
}

setExpirationDate(userId, date, prorector) {
    if (userId is primaryUserId) {
        setExpirationDate(date, protector)
    } else {
        reissuePrimaryUserId(userId, date)
    }
}

setExpirationDate(keyId, date, protector) {
    if (keyIsPrimaryKey) {
        setExpirationDate(date, protector)
    } else {
        reissueSubkeySignature(keyId, date, protector);
    }
}

//

setPrimaryUserId(userId, protector) {
    reissuePrimaryUserId(userId)
    if (hasDuplicatePrimaryUserIds) {
        reissueNonPrimaryUserIdsForDuplicates()
    }
}
```

**Comment by IvanPizhenko** [comment]
@vanitasvitae do you have any news here?

**Comment by vanitasvitae** [comment]
I will finally fix this now :)

**Comment by vanitasvitae** [comment]
Waaaah I have hit another stone :(

When describing the expiration period of a subkey, OpenPGP makes use of keyExpirationDate subpackets.

For user-id signatures, there is no dedicated expiration subpacket.
Instead, one has to rely on the signature expiration date subpacket, which describes when the signature itself expires.

If there is only a single user-id certification signature with a signature expiration period of 5 days, the user-id will become expired after 5 days.

The problem is, if there is more than one user-id signature for a single user-id.
In that case it is not possible with this pattern to "shorten" the expiration date period of the user-id.
The reason is, that if I create another signature with an expiration date closer to the current date, this signature will eventually expire, which will render the "older" user-id signature active again, so that the expiration date is again the old expiration date.

I'm not sure what the correct way of resolving this is.
OpenKeyChain apparently only takes the most recent user-id signature into consideration, meaning an expiring signature will not render an older signature valid again. This works, but is not what the specification states.

I will do some more research on how to resolve this situation.

Signatures in OpenPGP suuuuuuuck!

**Comment by vanitasvitae** [comment]
I sent [a mail](https://mailarchive.ietf.org/arch/msg/openpgp/C0P4MxwqJBbxS6H0YoXFF3oEJ3A/) to the IETF mailing list.

**Comment by IvanPizhenko** [comment]
@vanitasvitae Let's implement it now as you say OpenKeyChain does, just to unblock us. After that you may clarify this.

**Comment by IvanPizhenko** [comment]
So any chances to have working version in the nearest days?

**Comment by vanitasvitae** [comment]
I can't promise that, but I'll try.

One other thing: I took a look at how GnuPG designs their API and they don't even offer the option to set an expiration date of user-ids.

Instead you can set expiration dates for the primary or subkeys and merely revoke user-ids.
Since key expiration dates are always uniquely resolvable, this would dramatically decrease complexity.
Simplifying the API in that way could act as a workaround for this issue until we find a better solution for signature interpretation.

What do you say?

**Comment by vanitasvitae** [comment]
I opened #229

**Comment by IvanPizhenko** [comment]
How does this solve our practial issue? We have a keyring and we want to perform series of operations:
- changing primary user id
-  adding/removing secondary user ids
- changing key expiration
in the not known in advance order.
Will it make warranty that after each operation:
- if we have changed primary user id, key expiration and secondary user ids are preserved
- if we have changed key expiration, all user ids are preserved and primary one does not change
- if we have added secondary user id, primary user id and key expiration is preserved
- commonly used our and third party software, such as GnuPG, Thunderbird, MS Outlook, Flowcrypt browser extension (based on openpgp.js) looking at such key modified with PGPainless will interpret it in the same way?

**Comment by vanitasvitae** [comment]
I will try to make it work for these use cases.

**Comment by vanitasvitae** [comment]
Some more research later:

It appears GnuPG is completely replacing signatures on user-ids when switching primary user-id...
Sequoias `sq` tool doesn't support changing primary user-ids in a user-friendly way at all afaict.
What is right? What is wrong???

It sucks so much that the spec doesn't give any guidance on this whatsoever...

**Comment by vanitasvitae** [comment]
I guess for the long run, the cleanest solution for reducing user-id expirations would be to revoke older signatures directly using `SignautreTarget` subpackets.
The problem with this is, that BC doesn't expose the hash value of signatures and further the `SignatureTarget` class is only ever used in BC in test cases, so it is not clear to me how to use them correctly.

Unfortunately I haven't yet received a reply to my mail yet, so I'm unsure how to proceed. Sorry, that this issue drags out so much :/

**Comment by IvanPizhenko** [comment]
> Some more research later:
> 
> It appears GnuPG is completely replacing signatures on user-ids when switching primary user-id... Sequoias `sq` tool doesn't support changing primary user-ids in a user-friendly way at all afaict. What is right? What is wrong???
> 
> It sucks so much that the spec doesn't give any guidance on this whatsoever...

How do email clients react to this? I.e. assume you had the old key in Thunderbird. Then you modify key with GnuPG and what Thunderbird does when it gets that new modified key? What Outlook does? The correct way is the one which will allow us to perform these operations and will be compatible with existing email clients, even if it will be somewhat deviation from the spec or if spec doesn't specify anything.

**Comment by IvanPizhenko** [comment]
> I guess for the long run, the cleanest solution for reducing user-id expirations would be to revoke older signatures directly using `SignautreTarget` subpackets. The problem with this is, that BC doesn't expose the hash value of signatures and further the `SignatureTarget` class is only ever used in BC in test cases, so it is not clear to me how to use them correctly.
> 
> Unfortunately I haven't yet received a reply to my mail yet, so I'm unsure how to proceed. Sorry, that this issue drags out so much :/

I think it is a good question to ask on the BC mailing list.

**Comment by vanitasvitae** [comment]
Hey, just working on this and I have a question:

Do you need to have a dedicated `set{,Key,UserId}ExpirationDate()` method, or would you be okay if there was a `add{Primary}UserId(), addSubkey()` method that allows you to set an expiration date via some kind of argument?

**Comment by IvanPizhenko** [comment]
I'd prefer dedicated method set{something}. It will make the code significantly more readable and understandable.

**Comment by vanitasvitae** [comment]
Alright. My issue with this is, that it gives the impression that the class is some kind of builder while in fact every operation adds another signature to the key.

But I'll see what I can do.

**Comment by vanitasvitae** [comment]
Maybe I will name the methods accordingly (`addSignatureWithNewExpirationDate()` for example).

**Comment by IvanPizhenko** [comment]
Of course `addSignatureWithNewExpirationDate()` describes better what the method actually does, but do we really need that detail level? I was thinking this level of abstraction is down to BC, and PGPainless should be providing something more higher-level and end-user-friendly. Anyway, whatever you end up with, after you do it, please include some code examples which show how we should to use that.
Just to keep it focused: we want to do following things:
- change primary user id
- add and remove secondary user ids
- change key expiration date
- do above 3 multiple time in the almost random order and have consistent results across PGPainless itself, popular email clients like Thunderbird and MS Outlook and Flowcrypt browser extension (based on openpgp.js).

**Comment by vanitasvitae** [comment]
To reduce the scope of this down to the bare minimum:

What is the minimum API you need to set expiration dates for?
* [ ] whole key (primary key)
* [ ] single user-ids
* [ ] single subkeys

Edit: For me it would be the easiest to implement if we only would need `setExpirationDate()` for the whole key.
This method would either create a new primary user-id certification with expiration date (in case there is at least one user-id, so 99% of time), add a directKey-Signature with expiration date, or do both.

Expiring subkeys and user-ids could then be modeled using revocation.

**Comment by IvanPizhenko** [comment]
I believe we need "whole key (primary key)" in the first place. But to be completely sure, let's ask @tomholub. Tom, please clarify (see above question).

**Comment by vanitasvitae** [comment]
That would certainly be easiest for me.

**Comment by IvanPizhenko** [comment]
Even if it is not completely what actually needed, it will be a good starting point. So I think meanwhile you can proceed with it.

**Comment by tomholub** [comment]
Whole key. We don't need to set expiration for individual subkeys or user ids at all.

**Comment by vanitasvitae** [comment]
That's good news :P

**Comment by vanitasvitae** [comment]
If a key has a primary user-id "A" which has an expiration date of t1, do you expect that if you add a primary user-id "B", it copies "A"s expiration date?
Personally, I'm not sure how I would expect the API to function.

Copying the expiration date would mean that if I add "B" to an expired key, the key is still expired.

On the other hand, if I don't copy the expiration date, adding "B" to a key that expires at t1 would mean that t1 would get lost.

I'm torn on this. However, not copying the expiration date would be easiest to implement.

**Comment by vanitasvitae** [comment]
I will create another rc release containing changes to the key modification API, as well as fixes for security issues found by the audit.

Let me know, if this fixes your issue or if you encounter new problems :)

**Comment by tomholub** [comment]
> If a key has a primary user-id "A" which has an expiration date of t1, do you expect that if you add a primary user-id "B", it copies "A"s expiration date?

Absolutely. If I'm just adding another user, I don't expect that to change expiration, whether the key is expired or not.

**Comment by vanitasvitae** [comment]
Okay, I reworked the logic for setting primary user-ids once more, so that the expiration date of the old primary user-id is copied to the new primary user-id and also being removed from the new non-primary user-id sig on the old user-id.

PGPainless should now behave as expected, (I hope).

Release 1,0.0-rc7 has been published and should soon be available :)

Once you confirm that it fixes your issues I will release 1.0.0! \o/

**Comment by IvanPizhenko** [comment]
Thank you.

**Comment by vanitasvitae** [comment]
For the record, fixing this revealed a flaw in PGPainless' design, namely that it does only differentiate between valid and invalid signatures.

For advanced operations like re-certifying expired keys it would make much more sense to only consider correct, but expired signatures.

I will at some point need to rewrite signature evaluation to come up with an implementation that grants more control over when to reject signatures.

That would also be a great opportunity to improve exception texts for when a key is expired (get rid of those stupid NoSuchElementExceptions in favor for detailed messages like "The primary key is expired at XYZ".

**Comment by IvanPizhenko** [comment]
@vanitasvitae Something like this is what I've faced now. For the beginning, we may immediately need a method `KeyPairInfo.getValidAndExpiredUserIds()`, because `getValidUserIds()` no longer returns expired ones.

**Comment by IvanPizhenko** [comment]
I've found a method `getBoundButPossiblyExpiredUserIds()` - does it fit to above? 
Update: actually returns both expired and non-expired.
I'd suggest to change name of this method to  `getValidAndExpiredUserIds()`.

**Comment by vanitasvitae** [comment]
Good idea.

**Comment by IvanPizhenko** [comment]
@vanitasvitae Also we need a way to get expired primary user ID. Now, it seems like, if primary user ID is expired, it is no longer identified as primary and we get some other one, and while this may be correct with spec, we need to get exactly that expired one.

**Comment by IvanPizhenko** [comment]
@vanitasvitae We have two sample keys in which primary user ID has changed compared to previous PGPainless version:
- [keypair-uidtest-prv.asc.txt](https://github.com/pgpainless/pgpainless/files/7758254/keypair-uidtest-prv.asc.txt) - it was `uid2@test.com` but became `uid3@test.com`.
- [keypair-uidtest-updated-prv.asc.txt](https://github.com/pgpainless/pgpainless/files/7758271/keypair-uidtest-updated-prv.asc.txt) - it was `uid3@test.com` but became `uid4@test.com`.

Can you please investigate, why does that have happened and is this correct or not at all?
**Update:** maybe inconsistency on our side
**Update 2:** Rechecked, they are really different. I.e. for the sample keys above:
```kotlin
val info = PGPainless.inspectKeyRing(keyRing)
println(info.primaryUserId)
``` 
prints **different** primary user IDs.

**Comment by vanitasvitae** [comment]
None of these user-ids is carrying a primary user-id subpacket, so its up to the implementation to resolve this.
It turns out PGPainless previously just picked the first user-id it encountered in such case, while the updated implementation considers the latest certified user-id to be the primary one.

What do you think makes most sense? Should I revert to the old strategy?

**Comment by tomholub** [comment]
I think the first uid is a better guess to treat as primary in this case.

Often people will create keys with their main uid first, and then add additional ones later.

Of course, best would be that the keys are created with the right uids in the first place. Hopefully PGPainless does that now. But we could still encounter previous or other imported keys, and for that, treating the first non-primary uid as a primary (when there's a lack of a primary one) is I think best guess.

**Comment by vanitasvitae** [comment]
Sounds sensible.
I reverted the logic to return the first user-id. Also renamed the getter method to `getValidAndExpiredUserIds()`.

**Comment by IvanPizhenko** [comment]
So I'm waiting for the `rc8` version.

**Comment by IvanPizhenko** [comment]
> Okay, I reworked the logic for setting primary user-ids once more, so that the expiration date of the old primary user-id is copied to the new primary user-id and also being removed from the new non-primary user-id sig on the old user-id.
> 
> PGPainless should now behave as expected, (I hope).
> 
> Release 1,0.0-rc7 has been published and should soon be available :)
> 
> Once you confirm that it fixes your issues I will release 1.0.0! \o/

Looks like we will not let you release 1.0.0 very fast.

**Comment by vanitasvitae** [comment]
Released rc9 with a fix.

**Comment by IvanPizhenko** [comment]
@vanitasvitae 
I think you can now delete deprecated ones from the `KeyRingUtils`:
``` java
    @Deprecated
    public static PGPSecretKeyRing deleteUserId(PGPSecretKeyRing secretKeys, String userId)

    @Deprecated
    public static PGPPublicKeyRing deleteUserId(PGPPublicKeyRing publicKeys, String userId)
```
But instead please add directly into `SecretKeyRingEditorInterface`:
```kotlin
fun SecretKeyRingEditorInterface.deleteUserIds(
  userIdSelector: SelectUserId,
  secretKeyRingProtector: SecretKeyRingProtector
): SecretKeyRingEditorInterface {
  return this.revokeUserIds(
    userIdSelector,
    secretKeyRingProtector,
    DeleteUserIdRevocationSignatureSubpacketsCallback.instance
  )
}

fun SecretKeyRingEditorInterface.deleteUserId(
  userId: CharSequence,
  secretKeyRingProtector: SecretKeyRingProtector
): SecretKeyRingEditorInterface {
  return this.revokeUserId(userId, secretKeyRingProtector, DeleteUserIdRevocationSignatureSubpacketsCallback.instance)
}

class DeleteUserIdRevocationSignatureSubpacketsCallback : RevocationSignatureSubpackets.Callback {
  companion object {
    private val revocationAttributes = RevocationAttributes.createCertificateRevocation()
      .withReason(RevocationAttributes.Reason.USER_ID_NO_LONGER_VALID)
      .withDescription("Delete User ID")

    val instance: DeleteUserIdRevocationSignatureSubpacketsCallback by lazy {
      DeleteUserIdRevocationSignatureSubpacketsCallback()
    }
  }

  override fun modifyHashedSubpackets(hashedSubpackets: RevocationSignatureSubpackets?) {
    hashedSubpackets?.setRevocationReason(revocationAttributes)
  }
}

```

They can be described as "convenience" methods for `revoke`. These are very good candidates to move to PGPainless from our code.

**Comment by IvanPizhenko** [comment]
@vanitasvitae I also think we can move this one into PGPainless:

```kotlin
fun UserId.toUserIdSelectorByEmail(): SelectUserId =
  SelectUserId.or(
    SelectUserId.containsEmailAddress(email),
    SelectUserId.exactMatch(email)
  )
```
For completeness, you can add `toUserIdSelectorByNameAndEmail()` as well.

**Comment by IvanPizhenko** [comment]
@vanitasvitae rc8 worked for me, but I'd like we also to move the above code into PGPainless. Please prepare one more RC with these changes, and if it works, it can be finally 1.0.0.

**Comment by vanitasvitae** [comment]
Hey, sorry for being unresponsive the past days.
I hope you had nice holidays and I wish you a happy new year :fireworks:.

Adding the user-id deletion methods as convenience methods is a great idea, I added those as `removeUserId()`.
However, I'm not sure how much sense it makes to add the `DeleteUserIdRevocationSignatureSubpacketsCallback` class, as I was able to implement this without.

Interesting observation that `SelectUserId.containsEmailAddress("alice@pgpainless.org")` would not match "alice@pgpainless.org" due to the missing email parenthesis ('<', '>').

I added `SelectUserId.byEmail()` which implements `or(containsEmailAddress(), exactMatch())` as you suggested.

Now I will add some more tests and then push another release.

**Comment by vanitasvitae** [comment]
I released a (last?) snapshot (rc9) for you to try :)

**Comment by IvanPizhenko** [comment]
I hope so, but let us see...

**Comment by IvanPizhenko** [comment]
it works, but I think you need to add documentation comment for them.
Currently:
```java

    SecretKeyRingEditorInterface removeUserId(SelectUserId userIdSelector,
                                              SecretKeyRingProtector protector)
        throws PGPException;

    SecretKeyRingEditorInterface removeUserId(CharSequence userId,
                                              SecretKeyRingProtector protector)
        throws PGPException;
```
no documentation comments. Documentation comment should specifically state, that this is convenience method which actually revokes userId.

**Comment by vanitasvitae** [comment]
Right. I will add some docu later and then release 1.0.0 :)
