### ISSUE TITLE
Message is decrypted when it likely should not

### ISSUE THREAD

**Issue by IvanPizhenko** [vanitasvitae/pgpainless#228]
Note: I can't provide publicly exact message and key which I've tried. Please ask @tomholub is you need them.

Assume there is RSA 4096 keyring that consists of primary key (which is intended only for Sign and Certify), and subkey, which is intended only for Encrypt. And there is encrypted message (btw, created somehow with .NET version of BC) which encrypted for primary key (which is not intended for encryption). PGPainless successfully decrypts that (btw, GnuPG does too). While openpgp.js does not. Who is right is this case? Should we fix this in PGPainless? Or maybe this is upstream (BC) issue?

@tomholub FYI

**Comment by vanitasvitae** [comment]
This should be fixed in PGPainless.

**Comment by vanitasvitae** [comment]
I opened https://gitlab.com/sequoia-pgp/openpgp-interoperability-test-suite/-/issues/71 to add a test for this in the interoperability test suite.

Furthermore I have a working fix and am working on a test.

**Comment by vanitasvitae** [comment]
Fixed with https://github.com/pgpainless/pgpainless/commit/80e12db8b683193fcf4c4365a37b21498c8dbac4 and https://github.com/pgpainless/pgpainless/commit/5108b812521fba7444e30272988c7b991bccacd3

**Comment by vanitasvitae** [comment]
Hey @IvanPizhenko,
I couldn't find a mail address of yours, so this is the only way I know to contact you.
I hope you are alright and safe. Be assured that my thoughts and my solidarity are with you and your family in these days.
Please stay safe!

**Comment by IvanPizhenko** [comment]
Thanks Paul. Safe so far. Btw @DenBond7 is also from Ukraine.

**Comment by vanitasvitae** [comment]
Yeah I could reach him via mail. Luckily he is safe so far as well.

**Comment by vanitasvitae** [comment]
Edit: You should have received a mail with the original content.

**Comment by IvanPizhenko** [comment]
Hi Paul. Thank you for your message. We are keeping strong. But it is a bit scary, when you are on the street, going to the nearest grocery shop, and when hits even few km from you. That's what I have experienced today. Yes, the problem is that Russian army now targets with missiles even places where there is no military objects. You don't know if your place is next one.

**Comment by vanitasvitae** [comment]
I cannot imagine how scary that must be. I'm glad to hear from you though.

**Comment by DenBond7** [comment]
Hi @vanitasvitae. Thanks for your support and understanding!

> I'm writing you here, as it appears that mails are bouncing :/

It seems it's true. I haven't received any messages.

**Comment by vanitasvitae** [comment]
Hey @IvanPizhenko, I hope you are well.
Do you have an email address I can reach you at? It appears that some combinations of sender/receivers result in bouncing mails (riseup.net -> GMail bounces for example).

Stay strong!

**Comment by IvanPizhenko** [comment]
@vanitasvitae I've sent you an email.
