### ISSUE TITLE
How to omit the standard wordings in the encrypted file

### ISSUE THREAD

**Issue by hannah23280** [vanitasvitae/pgpainless#239]
Hi,

   When i use pgpainless to encrypt, the  encrypted file contains the below standard wordings.

-----BEGIN PGP MESSAGE-----
Version: PGPainless

-----END PGP MESSAGE-----

Is there a way not to include the above wordings ?

**Comment by vanitasvitae** [comment]
When you are talking about `Version: PGPainless`, you can change that to whatever you like by calling
```
ArmoredOutputStreamFactory.setVersionInfo("MyAwesomApp"); // whatever you like
```
It can however not be disabled currently when using ASCII armor.

The `-----BEGIN PGP MESSAGE-----` and `-----END PGP MESSAGE-----` are the ASCII armor.
If you do not want your output to be armored (results in binary ciphertext), you can call
```
ProducerOptions options = ProducerOptions.signAndEncrypt(
        // encryption and signing options
    );
options.setAsciiArmor(false); // <- Disable ASCII armoring
EncryptionStream encryptor = PGPainless.encryptAndOrSign()
                .onOutputStream(out)
                .withOptions(options);
```

**Comment by hannah23280** [comment]
Thanks. It works. Unfortunately, i cannot setVersionInfo to empty string.  So in the end, i did options.setAsciiArmor(false) to hide it.
