### ISSUE TITLE
UserID.equals() compares email addresses ignoring case

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/pgpainless#251]
Is that a good idea?

This may come as a surprise to the user.

**Comment by wiktor-k** [comment]
I'd lean on not being "too smart" with the code as that may indeed surprise users, like this one: https://stackoverflow.com/questions/2348399/why-does-java-net-urls-hashcode-resolve-the-host-to-an-ip

But the use case is valid. Maybe this can be done some other way eg. by providing an object that implements Comparator (not Comparable, https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html)?

Still, this may wait until someone asks for it :)

**Comment by vanitasvitae** [comment]
Good idea. I will think about it and keep your suggestion in mind :)

**Comment by vanitasvitae** [comment]
I added `UserId.compare(uid1, uid2, comparator)` along with some default comparators (one strict and one ignoring case).
This should give users a good idea on how to utilize comparators to their benefit.
