### ISSUE TITLE
Interop between PGPainless and gnupg broken. 

### ISSUE THREAD

**Issue by apple-corps** [vanitasvitae/pgpainless#275]
Hello,

I started trying to use bouncy castle to decrypt openPGP encrypted messages that were encrypted using gnupg.  I have since tried creating openPGP keys with PGPainless, encrypting messages with those generated keys using gnupg, and decrypting the messages using PGPainless.

I have already produced an example of the issue for bouncy castle. I receive a different exception using PGPainless. However, I believe it is likely caused by the same underlying issue. I am working on a reproduction for PGPainless. But until the interoperability issue is resolved it's a painful PGP experience.

**Comment by apple-corps** [comment]
https://github.com/bcgit/bc-java/issues/1151

**Comment by vanitasvitae** [comment]
I can happily report, that this issue is invalid :P

One issue I see is that your key has self-signatures on it made using SHA-1, which is rejected in PGPainless' default policy (and [other implementations](https://tests.sequoia-pgp.org/#Signature_over_the_shattered_collision)).
If you set a custom signature hash algorithm policy that allows SHA-1, decryption works as intended.

```java
        // Set a signature hash algorithm that accepts SHA1
        PGPainless.getPolicy().setSignatureHashAlgorithmPolicy(
                new Policy.HashAlgorithmPolicy(HashAlgorithm.SHA512, Arrays.asList(
                        HashAlgorithm.SHA512, HashAlgorithm.SHA384, HashAlgorithm.SHA256, HashAlgorithm.SHA224, HashAlgorithm.SHA1, HashAlgorithm.RIPEMD160
                )));

        // Load secret keys
        PGPSecretKeyRing secretKeys = PGPainless.readKeyRing().secretKeyRing(KEY);
        SecretKeyRingProtector protector = SecretKeyRingProtector.unlockAnyKeyWith(passphrase);

        // Load encrypted file
        InputStream cipherText = GnuPGInteropTest.class.getClassLoader().getResourceAsStream("launch-docker.sh.gpg");

        // Decrypt
        DecryptionStream decryptionStream = PGPainless.decryptAndOrVerify()
                .onInputStream(cipherText)
                .withOptions(new ConsumerOptions()
                        .addDecryptionKey(secretKeys, protector));

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Streams.pipeAll(decryptionStream, out);
        decryptionStream.close();

        OpenPgpMetadata metadata = decryptionStream.getResult();
        assertTrue(metadata.isEncrypted());

        System.out.println(out);
```

Output:
```
#docker run -it -v ./docker:/home/unknown GPG_TTY=/dev/console /bin/bash
docker run -it -v /Users/cwir4/Code/secrets/docker:/home/unknown -e GPG_TTY=/dev/console --entrypoint /bin/sh vladgh/gpg

```

**Comment by vanitasvitae** [comment]
I pushed the test case from above to [this branch](https://github.com/pgpainless/pgpainless/tree/issue_275) for you to compare :)

**Comment by apple-corps** [comment]
Thanks @vanitasvitae . I will take a look. At the EOD yesterday I created keys using PGPainless and encrypted a file using gpg and tried to decrypt using PGPainless. I am working on providing the reproduction here. But I will also see if your branch makes my error obvious.
