### ISSUE TITLE
expiration far in the future overflows

### ISSUE THREAD

**Issue by tomholub** [vanitasvitae/pgpainless#287]
Unsure if this is limitation of OpenPGP spec or the implementation

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/6306961/171356903-3ff27698-1b55-4e8a-8474-eda6e620b9eb.png">

**Comment by tomholub** [comment]
If limitation of spec, would be good to throw when attempting to set such date

**Comment by vanitasvitae** [comment]
At least key/signature creation dates are bound to an upper limit by the spec (something like year 2100 or so).

Expiration dates are usually calculated using an offset in seconds from creation time. However I thought this was represented by a 64 bit number. I will double check and create some tests for extreme cases :+1:.

**Comment by vanitasvitae** [comment]
I can definitely reproduce the described behavior.

**Comment by vanitasvitae** [comment]
I just pushed a fix which checks for IntegerOverflows and throws an `IllegalArgumentException` for expiration dates that would cause an overflow.

**Comment by tomholub** [comment]
Thanks :+1:
