### ISSUE TITLE
Definition of the isFullyDecrypted() and isFullyEncrypted()

### ISSUE THREAD

**Issue by IvanPizhenko** [vanitasvitae/pgpainless#299]
I wanted to migrate to PGPainless variant of `fullyDecrypted`, but found out following:

In our code we currently have following:
```kotlin
    val fullyDecrypted = if (keyRing is PGPSecretKeyRing) {
      // did the test again for Smart Cast encryption algorithm.
      // 0 means not encrypted. See https://tools.ietf.org/html/rfc4880#section-5.5.3
      keyRing.secretKeys.asSequence().all { it.keyEncryptionAlgorithm == 0 }
    } else {
      null // public key
    }
```

But in PGPainless it is:
```java
    // class KeyInfo

    public boolean isFullyDecrypted() {
        if (!isSecretKey()) {
            return true;
        }
        for (PGPSecretKey secretKey : getSecretKeys()) {
            if (!KeyInfo.hasDummyS2K(secretKey) && KeyInfo.isEncrypted(secretKey)) {
                return false;
            }
        }
        return true;
    }

    public static boolean isEncrypted(PGPSecretKey secretKey) {
        return secretKey.getS2KUsage() != 0;
    }
```
Is it equivalent or not? Which one's is more correct (judging by `keyEncryptionAlgorithm` or `S2KUsage`)?
Same thing affects `fullyEncrypted`.

**Comment by vanitasvitae** [comment]
Those are not completely equivalent.
Like the javadoc comment says:

> Sub-keys with S2K of a type GNU_DUMMY_S2K do not affect the result.

This means, if the key ring contains a subkey which uses a GNU_DUMMY_S2K (because the key was moved to a smartcard), the method will still return true, even though the key on the smartcard might be encrypted.

This is because we cannot deal with those keys anyways, so we just ignore them.

**Comment by IvanPizhenko** [comment]
@tomholub @vanitasvitae @Jerbell which one you think is more correct?

**Comment by tomholub** [comment]
Paul's implementation is more appropriate with regards to dummy keys.

As for the public key, we decided to go with null (not appropriate to encrypt) and Paul went with true, and neither is wrong, imo.

**Comment by Jerbell** [comment]
Both are correct. Personally I would have public key = true but it's not a big deal.

**Comment by vanitasvitae** [comment]
I'll close this as resolved. Feel free to reopen if there are any more questions :)
