### ISSUE TITLE
Documentation bug: `org.pgpainless.encryption_signing.EncryptionOptions` default subkey selection strategy

### ISSUE THREAD

**Issue by VolatileDream** [vanitasvitae/pgpainless#305]
It appears that the javadoc for `EncryptionOptions` was missed when updating the default subkey selection strategy as part of https://github.com/pgpainless/pgpainless/commit/9a485a3354410986153061375bc2f85f17937825.

The [javadoc claims](https://github.com/pgpainless/pgpainless/blob/b980fcd7b1fff3c12e07cdc8b5f8d47ab0091a27/pgpainless-core/src/main/java/org/pgpainless/encryption_signing/EncryptionOptions.java#L51-L67) the default is to select a single subkey for a recipient, but the default `EncryptionKeySelector` is actually `encryptToAllCapableSubkeys()`.

**Comment by vanitasvitae** [comment]
Good catch!
Indeed, the documentation needs to be updated here.
