### ISSUE TITLE
Question about usableForSigning

### ISSUE THREAD

**Issue by IvanPizhenko** [vanitasvitae/pgpainless#307]
Flowcrypt browser extension does following (using OpenPGP.js) to determine "usableForSigning": 

`usableforSigning` is defined as:
```ts
      usableForSigning: signingKey ? true : false,
```

`signingKey` is obtained as
```ts
    const { encryptionKey = undefined, encryptionKeyIgnoringExpiration = undefined, signingKey = undefined, signingKeyIgnoringExpiration = undefined }
      = isPrimaryKeyStrong ? await OpenPGPKey.getSigningAndEncryptionKeys(keyWithoutWeakPackets, exp, expired) : {};

```

where `exp` and `expired` are as follows:
```ts
    let exp: null | Date | number;
    try {
      exp = await keyWithoutWeakPackets.getExpirationTime('encrypt');
    } catch (e) {
      // tslint:disable-next-line: no-null-keyword
      exp = null;
    }

    const expired = () => {
      if (exp === Infinity || !exp) {
        return false;
      }
      // According to the documentation expiration is either undefined, Infinity
      // (typeof number) or a Date object. So in this case `exp` should never
      // be of type number.
      if (typeof exp === 'number') {
        throw new Error(`Got unexpected value for expiration: ${exp}`);
      }
      return Date.now() > exp.getTime();
    };
```

and `getSigningAndEncryptionKeys()` is:
```ts
  private static getSigningAndEncryptionKeys = async (key: OpenPGP.key.Key, exp: number | Date | null, expired: () => boolean) => {
    const getEncryptionKey = (keyid?: OpenPGP.Keyid | null, date?: Date, userId?: OpenPGP.UserId | null) =>
      key.getEncryptionKey(keyid, date, userId);
    const encryptionKey = await Catch.undefinedOnException(getEncryptionKey());
    const encryptionKeyIgnoringExpiration = encryptionKey ? encryptionKey : await OpenPGPKey.getKeyIgnoringExpiration(getEncryptionKey, exp, expired);
    const getSigningKey = (keyid?: OpenPGP.Keyid | null, date?: Date, userId?: OpenPGP.UserId | null) =>
      key.getSigningKey(keyid, date, userId);
    const signingKey = await Catch.undefinedOnException(getSigningKey());
    const signingKeyIgnoringExpiration = signingKey ? signingKey : await OpenPGPKey.getKeyIgnoringExpiration(getSigningKey, exp, expired);
    return { encryptionKey, encryptionKeyIgnoringExpiration, signingKey, signingKeyIgnoringExpiration };
  };
```

So finally it calls `key.getSigningKey(keyid, date, userId);`, this is OpenPGP.js method and it returns some key, even for public key (I've tested this).

As result, in Flowcrypt browser extension we can see that usableForEncryption is true.
But when we inspect public key in PGPainless, it returns isUsableForEncryption() == false.
I've looked into the code, and it turns that only secret key can be usable for encryption.

So my question is: what is the PGPainless based equivalent for a for public key of what the Flowcrypt browser extension does (as desribed above)? I guess it is:
```kt
  val info = PGPainless.inspectKeyRing(key)
  val usableForSigning = info.signingSubkeys.isNotEmpty()
```

@vanitasvitae Please confirm or suggest something better.

**Comment by vanitasvitae** [comment]
> As result, in Flowcrypt browser extension we can see that usableForEncryption is true.
But when we inspect public key in PGPainless, it returns isUsableForEncryption() == false.

Can you provide a test key for which you observe this behavior?

> I've looked into the code, and it turns that only secret key can be usable for encryption.

This is not the intended behavior at least.
Most of `KeyRingInfo`s methods act on the public keys of a key, as those "carry meaning" on their binding / certification signatures. The secret keys merely "enable certain actions" such as signing / decrypting.

~~However, `isUsableForXYZ()` should return the same result, no matter if executed on a `PGPSecretKeyRing` or its corresponding `PGPPublicKeyRing` as the result depends on the signatures on the public keys.~~ This is only true for `isUsableForEncryption()`, explanation below.

> So my question is: what is the PGPainless based equivalent for a for public key of what the Flowcrypt browser extension does (as desribed above)?

I see your issue I think. The OpenPGP.js method `usableForSigning` checks if the key/cert is valid and has a signing-capable subkey. The PGPainless method `KeyRingInfo.isUsableForSigning()` on the other hand also checks, if the key in question has the secret signing key available and hence only can ever return true, if the user inspects a PGPSecretKeyRing.

If you instead just want to know, if the certificate has a valid signing key and you don't care about whether the secret key is available (maybe you are inspecting a public key certificate and just want to display a check-mark in some UI), you can add the following extension function to `KeyRingInfo`:

```java
public boolean isCapableOfSigning() {
    // check if primary-key is revoked / expired
    if (!isKeyValidlyBound(getKeyId())) {
        return false;
    }
    // check if it has signing-capable key
    return !getSigningSubkeys().isEmpty();
}
```

In general I guess it is hard to choose method names which accurately describe what the intended purpose of the method is in this case.
`isUsableForSigning()/isUsableForEncryption()` really do check, if the particular action in question could be executed using this very key right now.

Perhaps we should add the above method as well? Can you think of better method names?

**Comment by IvanPizhenko** [comment]
Yes, please add such method.

**Comment by IvanPizhenko** [comment]
Thank you! Please publish a new version and let us know.

**Comment by vanitasvitae** [comment]
PGPainless 1.3.5 contains the fix and has been released to maven central :)

**Comment by IvanPizhenko** [comment]
Thank you!

**Comment by vanitasvitae** [comment]
Unrelated: If you are on Debian sid (unstable), you can now `apt install pgpainless-cli` :)

**Comment by IvanPizhenko** [comment]
That's cool, but I'm on Ubuntu 20.04.
