### ISSUE TITLE
Query on revocation

### ISSUE THREAD

**Issue by Jerbell** [vanitasvitae/pgpainless#327]
Hey,
Just a query - hopefully this doesn't take too long :)

When you revoke an OpenPGP key, it creates a `PGPSignature` with a creation time.

My query is - would it ever make sense to revoke in the future?
I see your `hasRevocation` doesn't seem to think so:
```java
    public boolean hasRevocation()
    {
        int ns = 0;
        boolean revoked = false;

        if (this.isMasterKey())    // Master key
        {
            while (!revoked && (ns < keySigs.size()))
            {
                if (((PGPSignature)keySigs.get(ns++)).getSignatureType() == PGPSignature.KEY_REVOCATION)
                {
                    revoked = true;
                }
            }
        }
        else                    // Sub-key
        {
            while (!revoked && (ns < subSigs.size()))
            {
                if (((PGPSignature)subSigs.get(ns++)).getSignatureType() == PGPSignature.SUBKEY_REVOCATION)
                {
                    revoked = true;
                }
            }
        }

        return revoked;
    }
```

**Comment by vanitasvitae** [comment]
Just to be clear; `PGPPublicKey` is not part of PGPainless, but part of the Bouncy Castle codebase instead :P

**Comment by Jerbell** [comment]
Ah sorry!  Just wondering what your opinion is mostly.  I have an opinion which seems to match the code above.

**Comment by vanitasvitae** [comment]
I think for when the user wants to *use* a key, they are mostly concerned with whether the key has a revocation *right now*.
This is what PGPainless does when evaluating a key using `PGPainless.inspectKeyRing()`.

**Comment by Jerbell** [comment]
Cool.  Looking at that method, you also have the concept of hard or soft revoke.  
Thanks - I'll close this.
