### ISSUE TITLE
ProducerOptions: hide armor meta

### ISSUE THREAD

**Issue by DenBond7** [vanitasvitae/pgpainless#328]
It would be nice to have an option like 

`producerOptions.hideArmorMeta = true`

to have just 

```
-----BEGIN PGP MESSAGE-----

hF4D16Pe22XLHvsSAQdAxqcSL8seB8mOidOEBRcPACKryPXXKq2jrtwruoD8MFMw
....
-----END PGP MESSAGE-----
```

instead of

```
-----BEGIN PGP MESSAGE-----
Version: PGPainless
Comment: Some comments

hF4D16Pe22XLHvsSAQdAxqcSL8seB8mOidOEBRcPACKryPXXKq2jrtwruoD8MFMw
....
-----END PGP MESSAGE-----
```

**Comment by vanitasvitae** [comment]
Implemented :)
I hope to get a new release out once BC 1.72.1 is published.

**Comment by DenBond7** [comment]
Thank you for the quick fix! New changes work well, I've tested them.

> I hope to get a new release out once BC 1.72.1 is published.

It seems it will be soon. `bcpg-jdk15to18` was already updated(yesterday) to [1.72.1](https://mvnrepository.com/artifact/org.bouncycastle/bcpg-jdk15to18)

**Comment by vanitasvitae** [comment]
> bcpg-jdk15to18 was already updated(yesterday) to [1.72.1](https://mvnrepository.com/artifact/org.bouncycastle/bcpg-jdk15to18)

Ah perfect! It seems I have missed that. Thanks for the notice!
