### ISSUE TITLE
pgpainless-cli: Please support special designator prefix `@FD:N`

### ISSUE THREAD

**Issue by dkg** [vanitasvitae/pgpainless#329]
Supporting a special designator prefix `@FD:NNN` (where `NNN` is an ASCII representation of an integer written in decimal) makes it possible for tooling to use `pgpainless-cli` without writing to the filesystem.

https://stackoverflow.com/questions/4845122/using-a-numbered-file-descriptor-from-java suggests that native Java can't do this directly, but on systems that support `/dev/fd/NNN` this can be worked around by just opening the corresponding path when present.

Perhaps `pgpainless-cli` could do that to support the file descriptor special designator on systems that support `/dev/fd/NNN` explicitly?

**Comment by vanitasvitae** [comment]
Closed in favor of https://github.com/pgpainless/sop-java/issues/12
