### ISSUE TITLE
pgpainless-cli: be less verbose in error cases

### ISSUE THREAD

**Issue by dkg** [vanitasvitae/pgpainless#331]
when pgpainless-cli 1.3.7 produces an error, i see a lot of backtrace material (e.g. #330).  This is surely interesting for pgpainless development, but it's pretty noisy for regular users.

If a signature verification fails, as a user i want to see a concise description of the failure to stderr, without the backtrace.

Could you make it less verbose in the default case?  (i certainly wouldn't object to some sort of generic `--debug` or `--verbose` flag for people who want the grubby details)

**Comment by vanitasvitae** [comment]
I created https://github.com/pgpainless/sop-java/issues/11 which is the better place for this issue.
To answer your question: Yes, this can be done, but it will probably take a bit of effort :D
