### ISSUE TITLE
sop commands output a Version Armor Header

### ISSUE THREAD

**Issue by guillemj** [vanitasvitae/pgpainless#336]
It looks like sop commands generating ASCII Armor output include a Version Armor Header. This is problematic as it means the output is different depending on the implementation used, and makes diffing or checking against reference files in test suites more annoying. Could the Version Armor Header be omitted?

**Comment by vanitasvitae** [comment]
Hm, this is a bit tricky.
I guess it totally makes sense to not print out the version header for the `armor` command.
However, for example the `generate-key` and `extract-cert` commands output additional armor comment headers containing the key/certs fingerprint and user-ids. Would you also want to hide those and have all armored output to be as "naked" as possible?

Armored encrypted / signed data is unpredictable in most cases anyways. Would you hide the version header there too?

**Comment by vanitasvitae** [comment]
For reference, `sqop generate-key` and `sqop extract-cert` also include a comment header with the keys/certs fingerprint.

**Comment by vanitasvitae** [comment]
I opened https://gitlab.com/dkg/openpgp-stateless-cli/-/issues/70 to ask for guidance in the SOP spec.

**Comment by guillemj** [comment]
I think the `Comment` from the `generate-key` and `extract-cert` are fine as these are reproducible output, compared to the `Version` one which will change depending on the implementation used. In addition the `generate-key` seems even less problematic as that's a command that will always generate unreproducible output anyway. :)

**Comment by vanitasvitae** [comment]
I opted for hiding the Version header by default in all SOP commands.
Comment headers are kept as they are currently.

I will soon create a new release containing the fixes. Thanks!
