### ISSUE TITLE
Add back `isEncrypted()`, `isSigned()` etc. to new `MessageMetadata` class

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/pgpainless#337]
Since `MessageMetadata` is intended to replace `OpenPgpMetadata` eventually, it should bring the same capabilities.

**Comment by vanitasvitae** [comment]
I added `isEncrypted()` and `isVerifiedSigned()` to the `MessageMetadata` class.

However, I am not sure about `isSigned()`.
Is it useful to have a method to determine, whether or not a message contained unverified signatures?
My concern is, that users might erroneously use `isSigned()` when in fact they really want to use `isVerifiedSigned()`.

But maybe it is enough to have `getRejected{Detached|Inline|OnePass}Signatures()` methods for users that want to check for the presence of unverified signatures.

**Comment by vanitasvitae** [comment]
I think I will not add `isSigned()` back. As stated above, `getRejected*Signatures()` should be sufficient to check for the presence of unverified signatures.

**Comment by bjansen** [comment]
I'm a bit late to the party, but I'm trying to upgrade to 1.4.1 and noticed that `isSigned()` is gone. We used it to provide a different message in the logs when
* a file is not signed at all
* a file is signed but not by someone we trust

For the first case I changed `!metadata.isSigned()` to `metadata.getVerifiedSignatures().isEmpty() && metadata.getRejectedInlineSignatures().isEmpty()` and I believe it should be enough (or so our unit tests say 😀).

To be clear, I'm not asking that you put the method back, I'm just informing you that at least one project used this method, but we can work it around 😉

**Comment by vanitasvitae** [comment]
> For the first case I changed !metadata.isSigned() to metadata.getVerifiedSignatures().isEmpty() && metadata.getRejectedInlineSignatures().isEmpty() and I believe it should be enough (or so our unit tests say grinning).

Yeah that should yield the same results for you :)

Thanks for letting me know. I hope you understand my reasoning behind this change :D
