### ISSUE TITLE
Bump bcpg to > 1.72.2

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/pgpainless#340]
The 1.72.2 release of bcpg contains some nice fixes for issues we ran into (e.g. gracefully parsing keys with unknown S2Ks).
However, the POM file appears to be broken (see https://github.com/bcgit/bc-java/issues/1281).
Therefore, I fear we probably need to wait for 1.72.3.

**Comment by DenBond7** [comment]
> Therefore, I fear we probably need to wait for 1.72.3.

It seems it is already available. (Just in case :))

On my side 1.72.3 has been already merged.
https://github.com/FlowCrypt/flowcrypt-android/pull/2084

**Comment by vanitasvitae** [comment]
Yeah, I was going to merge 1.72.3 into main today. :)
