### ISSUE TITLE
UserId class does not format email-only values properly

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/pgpainless#342]
`UserId.onlyEmail("alice@pgpainless.org").toString()` currently returns `alice@pgpainless.org`.
Same goes for `UserId.nameAndEmail("", "alice@pgpainless.org").toString()`.

I think it would be better, if by default these cases would return `<alice@pgpainless.org>`, since for example GnuPG's regex implementation only matches on mails inside of `<>`.
However, I am not sure if that breaks with existing implementations that rely on bare email addresses.

@DenBond7 @IvanPizhenko as you are likely affected by this, what do you think? Would you be okay with me changing the behavior of `UserId` to always wrap email addresses in `<>`?

**Comment by DenBond7** [comment]
On Android, I use [InternetAddress](https://github.com/jakartaee/mail-api/blob/master/api/src/main/java/jakarta/mail/internet/InternetAddress.java) to parse addresses. 

Where typical address syntax is of the form `"user@host.domain"` or `"Personal Name <user@host.domain>"`. I will check if `<alice@pgpainless.org>` affects the current code.

**Comment by DenBond7** [comment]
I've checked. A new approach works well.

![image](https://user-images.githubusercontent.com/2863246/204813014-71010986-a4d3-42f8-968b-674e95a4a531.png)

**Comment by vanitasvitae** [comment]
Great, then I will patch this for the upcoming 1.4 branch :)
Thanks for your input!

**Comment by IvanPizhenko** [comment]
It should be ok.
