### ISSUE TITLE
ConsumerOptions.ignoreMDCErrors is not used in OpenPgpMessageInputStream.processEncryptedData()

### ISSUE THREAD

**Issue by DenBond7** [vanitasvitae/pgpainless#354]
@vanitasvitae It seems after moving to use `OpenPgpMessageInputStream` the option `ConsumerOptions.ignoreMDCErrors` is not used now.

https://github.com/pgpainless/pgpainless/blob/7be12b0aaaca1bb5fcdecf55ef7e947cdc385986/pgpainless-core/src/main/java/org/pgpainless/decryption_verification/OpenPgpMessageInputStream.java#L411

Was it skipped?

1.3.14 - works
1.4.0 - doesn't work

**Comment by vanitasvitae** [comment]
You are right, I forgot to add in that check.
I will add a fix for the next release.

**Comment by vanitasvitae** [comment]
I added back the check and modified a test to verify that the configuration now works :)
