### ISSUE TITLE
Generate a keyring from an existing keypair

### ISSUE THREAD

**Issue by ebourg** [vanitasvitae/pgpainless#362]
I'd like to generate a PGP key from an existing private key, would it be possible to modify the builder to use an existing PGPKeyPair instead of generating a new one?

**Comment by vanitasvitae** [comment]
This sounds pretty edge-casey to me tbh.
What is the exact use-case you have in mind? Do you want to adopt existing subkeys into a new key with fresh primary key? Or do you simply want to reuse the key material in a new OpenPGP key (which also will have a new keyid + fingerprint due to changed creation date)?

Note that the later will mean that while technically it would be possible to use the "relabled" key to verify / decrypt messages generated with / for the old key, automatic matching of keys based on key-ids will no longer work, so when processing old messages might not work in some implementations (including PGPainless I think).

Lastly, PGPainless is still based on Bouncy Castle, so if you need this functionality for a one-shot thing, you can still use BCs classes to manually craft the new key to your liking. Let me know what you think :)

**Comment by ebourg** [comment]
Yes, the intent is to create a PGP key with the same key material as a PKCS key. I'm trying to do this to load an existing key into an OpenPGP card (such as a Yubikey or a Nitrokey) to perform code signing (with [Jsign](https://ebourg.github.io/jsign/)).

**Comment by vanitasvitae** [comment]
I think in that case your best bets would be to use BCs `PGPKeyRingGenerator` class similar to this:
```java
KeyFingerPrintCalculator keyFingerPrintCalculator = new BcKeyFingerprintCalculator();
        PGPDigestCalculator digestCalculator = new BcPGPDigestCalculatorProvider().get(HashAlgorithmTags.SHA1);

        BCPGKey underlyingPublicKey = ...; // There are algorithm-specific subclasses, e.g. RSAPublicBCPGKey, RSASecretBCPGKey
        BCPGKey underlyingPrivateKey = ...;
        
        Date creationDate = new Date(); // whatever
        int publicKeyAlgorithm = PublicKeyAlgorithmTags.RSA_GENERAL; // Choose fitting to your key

        // assemble the PGPKeyPair
        PublicKeyPacket publicKeyPacket = new PublicKeyPacket(publicKeyAlgorithm, creationDate, underlyingPublicKey);
        PGPPublicKey pgpPublicKey = new PGPPublicKey(publicKeyPacket, keyFingerPrintCalculator);
        PGPPrivateKey pgpPrivateKey = new PGPPrivateKey(pgpPublicKey.getKeyID(), publicKeyPacket, underlyingPrivateKey);
        PGPKeyPair keyPair = new PGPKeyPair(pgpPublicKey, pgpPrivateKey);

        // Prepare self-signature of primary key
        PGPSignatureSubpacketGenerator sigHashedSubpacketsGen = new PGPSignatureSubpacketGenerator();
        sigHashedSubpacketsGen.setKeyFlags(false, KeyFlags.CERTIFY_OTHER | KeyFlags.SIGN_DATA); // Feel free to add more keyflags, but CERTIFY_OTHER is MUST
        sigHashedSubpacketsGen.setFeature(false, Features.FEATURE_MODIFICATION_DETECTION);
        // Choose preferred algorithms to your liking
        sigHashedSubpacketsGen.setPreferredHashAlgorithms(false,
                new int[] {HashAlgorithmTags.SHA512, HashAlgorithmTags.SHA384, HashAlgorithmTags.SHA256});
        sigHashedSubpacketsGen.setPreferredCompressionAlgorithms(false,
                new int[] {CompressionAlgorithmTags.ZIP});
        sigHashedSubpacketsGen.setPreferredSymmetricAlgorithms(false,
                new int[] {SymmetricKeyAlgorithmTags.AES_256, SymmetricKeyAlgorithmTags.AES_192, SymmetricKeyAlgorithmTags.AES_128});

        PGPSignatureSubpacketVector hashedSubpackets = sigHashedSubpacketsGen.generate();
        // unhashed subpackets can be empty
        PGPSignatureSubpacketVector unhashedSubpackets = new PGPSignatureSubpacketGenerator().generate();

        PGPContentSignerBuilder signerBuilder = new BcPGPContentSignerBuilder(publicKeyAlgorithm, HashAlgorithmTags.SHA256);
        // Password-protection for the secret-key. Can be null for unencrypted key.
        PBESecretKeyEncryptor secretKeyEncryptor = new BcPBESecretKeyEncryptorBuilder(SymmetricKeyAlgorithmTags.AES_256)
                .build("keyPassword".toCharArray());

        PGPKeyRingGenerator keyRingGenerator = new PGPKeyRingGenerator(
                keyPair,
                digestCalculator,
                hashedSubpackets,
                unhashedSubpackets,
                signerBuilder,
                secretKeyEncryptor);

        // Add additional subkeys likethis
        // keyRingGen.addSubKey(anotherPGPKeyPair, anotherHashedSubpackets, anotherUnhashedSubpackets);

        PGPSecretKeyRing secretKeyRing = keyRingGenerator.generateSecretKeyRing();
        PGPPublicKeyRing publicKeyRing = PGPainless.extractCertificate(secretKeyRing);

        // voila
```

You only need to figure out the part where you convert your PKCS key to public and secret BCPGKey.
Note: This code is untested, but should roughly do what you want to accomplish.

Edit: Changed digestCalculator to SHA1.

**Comment by ebourg** [comment]
Thank you, I'll give it a try. I have the part to generate the keypair already, it looks like this:

    if (key instanceof BCRSAPrivateCrtKey) {
        BCRSAPrivateCrtKey privateKey = (BCRSAPrivateCrtKey) key;
        KeySpec keySpec = new RSAPublicKeySpec(privateKey.getModulus(), privateKey.getPublicExponent());
        PublicKey publicKey = KeyFactory.getInstance("RSA").generatePublic(keySpec);
        KeyPair keyPair = new KeyPair(publicKey, privateKey);

        return new JcaPGPKeyPair(PGPPublicKey.RSA_GENERAL, keyPair, new Date());

    } else {
        BCECPrivateKey privateKey = (BCECPrivateKey) key;
        ECPublicKeySpec keySpec = new ECPublicKeySpec(privateKey.getParams().getGenerator(), privateKey.getParams());
        BCECPublicKey publicKey = new BCECPublicKey(privateKey.getAlgorithm(), keySpec, BouncyCastleProvider.CONFIGURATION);
        KeyPair keyPair = new KeyPair(publicKey, privateKey);

        return new JcaPGPKeyPair(PGPPublicKey.ECDSA, keyPair, new Date());
    }

But the keyring generation for an EC didn't work (no valid user, something wrong with the signature).

**Comment by vanitasvitae** [comment]
Hm, note that not every EC key can be used within OpenPGP. See https://www.rfc-editor.org/rfc/rfc6637 and https://datatracker.ietf.org/doc/html/draft-koch-eddsa-for-openpgp-00 for currently used elliptic curve algorithms in OpenPGP.

**Comment by ebourg** [comment]
I've figured it out, they EC public key was not properly constructed, but Bouncy Castle didn't complain.

Here is the correct way:

      BCECPrivateKey privateKey = (BCECPrivateKey) key;
      ECPublicKeySpec pubSpec = new ECPublicKeySpec(privateKey.getParameters().getG().multiply(privateKey.getD()), privateKey.getParameters());
      BCECPublicKey publicKey = new BCECPublicKey(privateKey.getAlgorithm(), pubSpec, BouncyCastleProvider.CONFIGURATION);
      KeyPair keyPair = new KeyPair(publicKey, privateKey);
  
      return new JcaPGPKeyPair(PGPPublicKey.ECDSA, keyPair, creationDate);

This works with a P-384 curve, OID 1.3.132.0.34 (secp384r1), which is mentioned in RFC 6637.

I wrote my own keyring generator, but pgpainless can still be used to do this by copying `KeyRingBuilder` and changing the `generateKeyPair` method to return the prebuilt keypair (If the method wasn't static it could be simply overridden).

Thank you for the help.
