### ISSUE TITLE
Decryption with a protected private key fails without a password

### ISSUE THREAD

**Issue by webjoin** [vanitasvitae/pgpainless#363]
/** Test class */
public class PgpEncryptDecryptTest {
    String secretKey;
    String publicKey;
    String userId = "pgp@pgp.com";

   void generateKey(String passphrase) {
        try {
            PGPSecretKeyRing secretKey =
                PGPainless.generateKeyRing().simpleRsaKeyRing(userId, RsaLength._3072, passphrase);
            this.secretKey = PGPainless.asciiArmor(secretKey);
            secretKey = PGPainless.readKeyRing().secretKeyRing(this.secretKey);
            PGPPublicKeyRing publicKey = PGPainless.extractCertificate(secretKey);
            this.publicKey = PGPainless.asciiArmor(publicKey);
        } catch (IOException | InvalidAlgorithmParameterException | NoSuchAlgorithmException | PGPException e) {
            throw new RuntimeException(e);
        }
    }

 
    @Test
    void test_decrypt_fail_with_passphrase() throws IOException, PGPException {
        String passphrase = RandomStringUtils.randomAscii(10); // code 1
        generateKey(passphrase);

        String message = "Hello PGP";
        PGPPublicKeyRing certificateAlice = PGPainless.readKeyRing().publicKeyRing(publicKey);
        ByteArrayOutputStream ciphertext = new ByteArrayOutputStream();
        EncryptionOptions encryptionOptions = EncryptionOptions.encryptCommunications().addRecipient(certificateAlice)
        // .addPassphrase(Passphrase.fromPassword("messagePassphrase")) // code 2
       ;
        EncryptionStream encryptor = PGPainless.encryptAndOrSign().onOutputStream(ciphertext)
            .withOptions(ProducerOptions.encrypt(encryptionOptions).setAsciiArmor(true));
        Streams.pipeAll(new ByteArrayInputStream(message.getBytes(StandardCharsets.UTF_8)), encryptor);
        encryptor.close();
        String encrypted = ciphertext.toString();
        System.out.printf("ciphertext：%s%n", encrypted);

        // decrypt
        try {
            PGPSecretKeyRing keyAlice = PGPainless.readKeyRing().secretKeyRing(secretKey);
            SecretKeyRingProtector protectorBob = SecretKeyRingProtector.unprotectedKeys();
            // add the decryption key ring
            ConsumerOptions consumerOptions = new ConsumerOptions().addDecryptionKey(keyAlice, protectorBob)
           // .addDecryptionPassphrase(Passphrase.fromPassword("messagePassphrase")) // code 3
           ;
            ByteArrayOutputStream plaintextOut = new ByteArrayOutputStream();
            ByteArrayInputStream ciphertextIn = new ByteArrayInputStream(encrypted.getBytes(StandardCharsets.UTF_8));
            DecryptionStream decryptionStream =
                PGPainless.decryptAndOrVerify().onInputStream(ciphertextIn).withOptions(consumerOptions);
            Streams.pipeAll(decryptionStream, plaintextOut);
            decryptionStream.close();
            Assertions.assertEquals(message, plaintextOut.toString());
        } catch (WrongPassphraseException e) {
            assertTrue(e.getMessage().startsWith("Wrong passphrase provided for key")); // code 4
        }
    }
}

Hello pgpainless, 
1. (code 1) is a passphrase used to generate keys.
2. (code 2) and (code 3) do not specify a password。
3. it will get a  WrongPassphraseException. (code 4)

My question is that:
If the passphrase is used to protect the secretKey when producing the key, the encryption and decryption must use the same non-empty passphrase to complete the encryption and decryption. In this case, if encryption does not use passphrase, is it possible to decrypt without using passphrase? How to adjust the code?

**Comment by vanitasvitae** [comment]
You are confusing two separate uses for passwords: Protecting secret keys with a passphrase, and encrypting messages symmetrically using a per-message passphrase (e.g. your code 2, 3).

```
PGPSecretKeyRing secretKey = PGPainless.generateKeyRing().simpleRsaKeyRing(userId, RsaLength._3072, passphrase);
```
Here, passphrase is used to password-protect the secret key. A password-protected secret key requires the passphrase whenever it is used to sign a message or decrypt an encrypted message. You can provide the passphrase to sign or decrypt operations using the SecretKeyRingProtector. In your case, you can do the following:

```
// decrypt
PGPSecretKeyRing keyAlice = PGPainless.readKeyRing().secretKeyRing(secretKey);
SecretKeyRingProtector protectorAlice = SecretKeyRingProtector.unlockAnyKeyWith(passphrase);
ConsumerOptions consumerOptions = new ConsumerOptions().addDecryptionKey(keyAlice, protectorAlice)
...
```

Encrypting a message with a password is separate from encryption using a public key.

Please also read https://pgpainless.readthedocs.io/en/latest/pgpainless-core/passphrase.html

**Comment by webjoin** [comment]
Thank you very much!  it works. I will read it.
