### ISSUE TITLE
Misleading @Nullable annotation on the `KeyRingInfo.getLastModified()`

### ISSUE THREAD

**Issue by IvanPizhenko** [vanitasvitae/pgpainless#364]
Hi Paul,
First of all, thank you for this huge banner "Help Ukraine now!".

I have found following:
```java
    public @Nullable Date getLastModified() {
        PGPSignature mostRecent = getMostRecentSignature();
        if (mostRecent == null) {
            // No sigs found. Return public key creation date instead.
            return getLatestKeyCreationDate();
        }
        return mostRecent.getCreationTime();
    }
```
But neither `getLatestKeyCreationDate()` nor `mostRecent.getCreationTime()` can return null.
So this annotation should be removed or replaced with `@Nonnull`.

**Comment by vanitasvitae** [comment]
> First of all, thank you for this huge banner "Help Ukraine now!".

It's been up for almost a year now, and it will stay up as long as necessary.

> But neither getLatestKeyCreationDate() nor mostRecent.getCreationTime() can return null.
So this annotation should be removed or replaced with @Nonnull.

Good catch! I will fix it.
