### ISSUE TITLE
Key does not have a valid/acceptable signature to derive an expiration date from

### ISSUE THREAD

**Issue by sushengloong** [vanitasvitae/pgpainless#371]
Hi, I encountered the exception below while trying to encrypt and sign something with pgpainless-sop. 
```
Caused by: org.pgpainless.exception.KeyException$UnacceptableSelfSignatureException: Key 87518BFC11C9B490C8980F489E459E50958DA71F does not have a valid/acceptable signature to derive an expiration date from.
```

My code is as follows:
```
byte[] ciphertext = sop.encrypt()
                    .withCert(publicKey)
                    .signWith(secretKey)
                    .withKeyPassword("password")
                    .plaintext(plaintext.getBytes())
                    .getBytes();
```

It looks like `withCert` is unable to use the publicKey but I can't figure out what to fix based on the exception message.

Furthermore, I was able to encrypt and sign with the same keys using the `gnupg` command on my local machine (Mac OS) so I am not sure what I am missing. Any help is appreciated!

**Comment by vanitasvitae** [comment]
Hey!
PGPainless might be using a stricter algorithm policy than GnuPG, so it is very likely that the keys you try to use do use algorithms (or signatures made using algorithms) which are rejected by PGPainless.

I can recommend the [sequoia-keyring-linter](https://crates.io/crates/sequoia-keyring-linter) to check what the exact issue is. The tool can even try to fix the issue for your own key.

If the issue persists (or you are unable to modify affected keys, e.g. if they are public keys of contacts) you can try to [relax PGPainless' algorithm policy](https://pgpainless.readthedocs.io/en/latest/quickstart.html#weak-keys-and-broken-algorithms).
If the issue still persists, let me know :)

**Comment by sushengloong** [comment]
Hi @vanitasvitae,

I was able to get it working after relaxing the hash algorithm policy to allow SHA1 (I can't modify the key).

```java
Policy policy = PGPainless.getPolicy();
Policy.HashAlgorithmPolicy customPolicy = new Policy.HashAlgorithmPolicy(
        HashAlgorithm.SHA512,
        Arrays.asList(HashAlgorithm.SHA512, HashAlgorithm.SHA384, HashAlgorithm.SHA256, HashAlgorithm.SHA224, HashAlgorithm.SHA1));
policy.setSignatureHashAlgorithmPolicy(customPolicy);
```

Thank you so much for your help!

**Comment by vanitasvitae** [comment]
Glad to hear :)

**Comment by vanitasvitae** [comment]
Reference: #373
