### ISSUE TITLE
org.pgpainless.exception.MissingDecryptionMethodException: No working decryption method found.

### ISSUE THREAD

**Issue by sushengloong** [vanitasvitae/pgpainless#372]
Hi, I am trying to decrypt a cipher text but keep getting `java.lang.RuntimeException: org.pgpainless.exception.MissingDecryptionMethodException: No working decryption method found.` 

The code looks something like this:-

```java
PGPSecretKeyRing secretKey = PGPainless.readKeyRing().secretKeyRing(secretKeyIs); 
SecretKeyRingProtector secretKeyProtector = SecretKeyRingProtector.unlockAnyKeyWith(Passphrase.fromPassword("password"));
PGPPublicKeyRing signerPublicKey = PGPainless.readKeyRing().publicKeyRing(signerPublicKeyIs);
...
DecryptionStream decryptionStream = PGPainless.decryptAndOrVerify()
       .onInputStream(new ByteArrayInputStream(cipherText.getBytes()))
       .withOptions(new ConsumerOptions()
               .addDecryptionKey(secretKey, secretKeyProtector)
               .addVerificationCert(signerPublicKey)
       );
ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
Streams.pipeAll(decryptionStream, outputStream);
decryptionStream.close();
```

What am I missing? Any help is appreciated!

**Comment by vanitasvitae** [comment]
Are you sure you are using the correct secret key to decrypt the message?
Can you post a more complete stacktrace?

**Comment by sushengloong** [comment]
I was able to decrypt the message using the same secret key and gnupg on my machine.

This is the relevant stack trace. Apparently it couldn't recognize the secret key or password that I set. Strange. Any clue?

```
Caused by: sop.exception.SOPGPException$CannotDecrypt: No usable decryption key or password provided.
	at org.pgpainless.sop.DecryptImpl.ciphertext(DecryptImpl.java:127) ~[pgpainless-sop-1.5.0.jar:na]
	at sop.operation.Decrypt.ciphertext(Decrypt.java:191) ~[sop-java-6.0.0.jar:na]
	... 52 common frames omitted
Caused by: org.pgpainless.exception.MissingDecryptionMethodException: No working decryption method found.
	at org.pgpainless.decryption_verification.OpenPgpMessageInputStream.consumePackets(OpenPgpMessageInputStream.java:311) ~[pgpainless-core-1.5.0.jar:na]
	at org.pgpainless.decryption_verification.OpenPgpMessageInputStream.<init>(OpenPgpMessageInputStream.java:227) ~[pgpainless-core-1.5.0.jar:na]
	at org.pgpainless.decryption_verification.OpenPgpMessageInputStream.create(OpenPgpMessageInputStream.java:166) ~[pgpainless-core-1.5.0.jar:na]
	at org.pgpainless.decryption_verification.OpenPgpMessageInputStream.create(OpenPgpMessageInputStream.java:136) ~[pgpainless-core-1.5.0.jar:na]
	at org.pgpainless.decryption_verification.OpenPgpMessageInputStream.create(OpenPgpMessageInputStream.java:116) ~[pgpainless-core-1.5.0.jar:na]
	at org.pgpainless.decryption_verification.DecryptionBuilder$DecryptWithImpl.withOptions(DecryptionBuilder.java:39) ~[pgpainless-core-1.5.0.jar:na]
	at org.pgpainless.sop.DecryptImpl.ciphertext(DecryptImpl.java:125) ~[pgpainless-sop-1.5.0.jar:na]
	... 54 common frames omitted
```

**Comment by vanitasvitae** [comment]
Hm, this could be caused by a policy issue again.
Have you applied the same relaxed hash algorithm policy as in #371?
Can you give some details on the used key? Perhaps it is an RSA key with less than 2000 bits?

If you enable debug logging (e.g. by adding logback or another slf4j-compatible logger and enable debug level messages), you should be able to get some more clues as to why PGPainless fails to decrypt the message.

**Comment by sushengloong** [comment]
> Have you applied the same relaxed hash algorithm policy as in https://github.com/pgpainless/pgpainless/issues/371?

Yes I have but still no luck.

> Can you give some details on the used key? Perhaps it is an RSA key with less than 2000 bits?

It's an RSA key with 3072 bits and is protected with a passphrase.

> If you enable debug logging (e.g. by adding logback or another slf4j-compatible logger and enable debug level messages), you should be able to get some more clues as to why PGPainless fails to decrypt the message.

I enabled debug logging and the log messages are as follows.

```
20:27:37.805 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Symmetrically Encrypted Data Packet at depth 0 encountered
20:27:37.805 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Symmetrically Encrypted Data Packet at depth 0 encountered
20:27:37.806 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Symmetrically Encrypted Integrity-Protected Data has 0 SKESK(s) and 1 PKESK(s) from which 0 PKESK(s) have an anonymous recipient
20:27:37.806 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Symmetrically Encrypted Integrity-Protected Data has 0 SKESK(s) and 1 PKESK(s) from which 0 PKESK(s) have an anonymous recipient
20:27:37.806 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Encountered PKESK for recipient 99AAE21A373F9F01
20:27:37.806 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Encountered PKESK for recipient 99AAE21A373F9F01
20:27:37.807 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Subkey 99aae21a373f9f01 cannot be used for decryption.
20:27:37.807 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Subkey 99aae21a373f9f01 cannot be used for decryption.
20:27:37.807 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Skipping PKESK because no matching key 99AAE21A373F9F01 was provided
20:27:37.807 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Skipping PKESK because no matching key 99AAE21A373F9F01 was provided
20:27:37.807 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Failed to decrypt encrypted data packet
20:27:37.807 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Failed to decrypt encrypted data packet
```

I am not sure if I understand what was going on. The `Skipping PKESK because no matching key 99AAE21A373F9F01 was provided` looks suspicious enough but the key matches the right secret key.

**Comment by vanitasvitae** [comment]
> 20:27:37.807 [reactor-http-nio-2] DEBUG o.p.d.OpenPgpMessageInputStream - Subkey 99aae21a373f9f01 cannot be used for decryption.

This line is probably closest to the cause.

I'd assume that [this code block](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/main/java/org/pgpainless/decryption_verification/OpenPgpMessageInputStream.java#L695-L700) does not yield your encryption key.
The reason might be that the self-signature on the key is not valid (e.g. expired, revoked, uses outdated algorithms), or that the self-signature does not mark the key as encryption capable via the respective key-flags.

Could you try to set a break-point into [this line](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/main/java/org/pgpainless/key/info/KeyRingInfo.java#L913) and then step through the method to check if you can identify, which if-statement in the method causes a `continue`?

In the mean time, I created #373 to have better error reporting in the future.

**Comment by sushengloong** [comment]
> Could you try to set a break-point into [this line](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/main/java/org/pgpainless/key/info/KeyRingInfo.java#L913) and then step through the method to check if you can identify, which if-statement in the method causes a continue?

I stepped through the method and it turns out that those `continue`s did not happen. 

On the other hand, it does look like the secret key indeed does not have a subkey that matches the key id.

<img width="1323" alt="debug" src="https://user-images.githubusercontent.com/929772/234015359-fe53acc3-05a8-49a9-9472-772c680441e0.png">

I printed the secret key using gnupg.

```
pub   rsa3072/99AAE21A373F9F01 2023-04-17 [SC]
      A76CBA31D5C48F20B5946B5D99AAE21A373F9F01
uid                 [ unknown] REDACTED <redacted@example.com>
sub   rsa3072/11C61559E5385959 2023-04-17 [E]
```

**Comment by sushengloong** [comment]
> In the mean time, I created https://github.com/pgpainless/pgpainless/issues/373 to have better error reporting in the future.

👍 thanks for doing that!

**Comment by vanitasvitae** [comment]
Ah!

It appears that the message you are trying to decrypt was produced by some legacy application that erroneously used the primary key `99AAE21A373F9F01` for encryption instead of using the encryption subkey `11C61559E5385959`. Can you perhaps share what application produced that message?

The primary key is marked [SC], which means it is intended for signing messages and creating certifications only.
The subkey is marked [E], so *it* is intended for encryption.

Currently, PGPainless enforces these constraints and refuses to decrypt with a key that is not marked as encryption capable.
I might reconsider this for a future release though, to increase compatibility with faulty legacy clients. Or maybe I'll just add a config flag to allow decryption using non-encryption keys.

**Comment by sushengloong** [comment]
I see and thanks for your explanation and patience! The message was produced by an external banking API which is a black box to me unfortunately. 

gnupg does allow the decryption (which is why it was confusing to me at first) so I think it makes sense for PGPainless to allow such decryption by default too. Otherwise, adding a config flag also sounds good to me.

**Comment by vanitasvitae** [comment]
> The message was produced by an external banking API which is a black box to me unfortunately.

I see. Maybe consider reporting it to them anyways, so that the OpenPGP ecosystem can advance ;)

**Comment by vanitasvitae** [comment]
I just released PGPainless 1.5.1 (should be on Maven Central in an hour or so).
Let me know if this fixes your issue :)

**Comment by sushengloong** [comment]
Yes, the new version works like a charm and my issue has been resolved! Thank you very much!

**Comment by vanitasvitae** [comment]
Awesome! Thanks for your bug report ;)
