### ISSUE TITLE
check that a message was not encrypted by public keys

### ISSUE THREAD

**Issue by DenBond7** [vanitasvitae/pgpainless#376]
Hi @vanitasvitae 

How can I check that a message was not encrypted by public keys? For example, check that it was encrypted only by password

```
val encOpt = EncryptionOptions().apply {
      addPassphrase(passphrase) 
}
```

For `OpenPgpMetadata` I used to use `assertEquals(setOf<Long>(), decryptionResult.openPgpMetadata?.recipientKeyIds)`

What about `MessageMetadata`?

**Comment by vanitasvitae** [comment]
You can do
```java
MessageMetadata metadata = decryptionStream.getMetadata();
assertTrue(metadata.getEncryptionLayers().next().getRecipients().isEmpty());
```

**Comment by DenBond7** [comment]
Thank you!

**Comment by vanitasvitae** [comment]
Addendum: While realistically there is only one encryption layer in OpenPGP messages, it probably doesn't hurt to iterate over all items of the iterator and check if their recipients are empty.

**Comment by DenBond7** [comment]
To be honest, I did that way :)

**Comment by vanitasvitae** [comment]
I added `messageMetadata.getRecipientKeyIds()` :)
