### ISSUE TITLE
java.lang.NoSuchMethodError when attempting to decrypt

### ISSUE THREAD

**Issue by LazaroR94** [vanitasvitae/pgpainless#382]
Hello, I have recently been seeing this strange error in my application when trying to decrypt an incoming file: `java.lang.NoSuchMethodError: 'org.bouncycastle.bcpg.BCPGInputStream org.bouncycastle.bcpg.BCPGInputStream.wrap(java.io.InputStream)'`. I have no idea why this error is coming but I can only assume this is because it's missing some other bounty-castle dependency of some sort? This is how my decryption is set-up (Kotlin):
```
fun decryptPgpFile(inputStream: ByteArrayInputStream): DecryptionStream {
        return pgPainlessHelper.decryptAndOrVerify().onInputStream(inputStream).withOptions(pgpConsumerOptions)
    }
```

Any ideas as to why I may be getting that error?

**Comment by vanitasvitae** [comment]
You most likely use an older version of BouncyCastle in your project. Latest PGPainless should pull in BC 1.73.

How do you include PGPainless in your build?

**Comment by LazaroR94** [comment]
These are my only two dependencies for PGPainless in my project (as far as I can tell):
```
implementation("org.pgpainless:pgpainless-core:1.4.2")
implementation("org.pgpainless:pgpainless-sop:1.4.4")
```

**Comment by LazaroR94** [comment]
I also believe one of our dependencies pulls in this BouncyCastle dependency (transitively):
```
<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpg-jdk15on</artifactId>
            <version>1.68</version>
        </dependency>
```

**Comment by vanitasvitae** [comment]
There is a version mismatch between pgpainless-core and pgpainless-sop.
Using the same version should resolve this.

**Comment by vanitasvitae** [comment]
(pgpainless-sop internally depends on pgpainless-core, so if pgpainless-core 1.4.2 and pgpainless-core 1.4.4 depend on different versions of Bouncycastle, things might break).

**Comment by LazaroR94** [comment]
So I just tested this again with both versions being 1.4.4 and I still observe this issue unfortunately.

**Comment by vanitasvitae** [comment]
Hm, could you try to [exclude](https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991/2) BC 1.68 from the dependency that pulls it in and try again?

**Comment by LazaroR94** [comment]
I just did and even upgraded both PGPainless libraries to 1.5.1 and nothing. I've excluded that transitive dependency from two similar libraries as well.

**Comment by vanitasvitae** [comment]
This must be a bug with your build system then.
The method in question was added to BouncyCastle [8 months ago](https://github.com/bcgit/bc-java/blame/master/pg/src/main/java/org/bouncycastle/bcpg/BCPGInputStream.java#L23) and has been part of BC since then.
In your project there must be another, older version that gets referenced somehow, so that the method cannot be found.

Unfortunately I am out of ideas how to debug this.

**Comment by LazaroR94** [comment]
I see a lot of dependencies using this transitive dependency whereas yours uses a different artifact ID altogether, could this be the cause perhaps? `org.bouncycastle:bcprov-jdk15on:1.70`

Your library uses these under-the-hood:
```
+--- org.bouncycastle:bcprov-jdk15to18:1.73
|    \--- org.bouncycastle:bcpg-jdk15to18:1.73
```

**Comment by vanitasvitae** [comment]
PGPainless targets Java 8 and below, so it includes `*-jdk15to18`, as `-jdk18on` could include code targeting Java 8 API > 8.

At some point BC renamed their releases from `-jdk15on` to `jdk-15to18` and introduced `jdk18on` instead iirc.

**Comment by vanitasvitae** [comment]
I think excluding `bcpg-jdk15on:1.68` should fix the issue.
The issue is definitely caused by a wrongly included `bcpg-` jar.

**Comment by LazaroR94** [comment]
My apologies, it was indeed user error on my behalf. I have solved this by adding this snippet of code to my build.gradle.kts:
```
configurations {
    all {
        exclude(group = "org.bouncycastle", module = "bcpg-jdk15on")
    }
}
```

In the end, thank you so much for your patience haha.

**Comment by vanitasvitae** [comment]
Glad I could help :)
