### ISSUE TITLE
kbx support ?

### ISSUE THREAD

**Issue by bodhi-one** [vanitasvitae/pgpainless#396]
Does pgpainless have support for use of .kbx files down into the bouncycastle API?  I checked the sources and didn't see that.

**Comment by vanitasvitae** [comment]
PGPainless currently does not support GnuPG KeyBox files.
I know that Bouncy Castle has [some support for it](https://github.com/bcgit/bc-java/tree/main/pg/src/main/java/org/bouncycastle/gpg/keybox), but I have not looked into that too much, so I cannot give any guidance on how to extract keys from the kbx format.

**Comment by vanitasvitae** [comment]
It appears there are some [tests which demonstrate](https://github.com/bcgit/bc-java/blob/main/pg/src/test/java/org/bouncycastle/gpg/test/KeyBoxTest.java) how to the BCs KeyBox support.
Notably, you can extract PGPPublicKeyRing objects from the keybox as shown [here](https://github.com/bcgit/bc-java/blob/main/pg/src/test/java/org/bouncycastle/gpg/test/KeyBoxTest.java#L163).

Support for kbx files natively in PGPainless is not on my roadmap, so unless there is [serious interest to have this implemented inside PGPainless](https://github.com/pgpainless/pgpainless#professional-support), you need to do away with a wrapper that extracts PGPPublicKeyRings from the keybox file and passes them to PGPainless.
