### ISSUE TITLE
Java 17 compatibility

### ISSUE THREAD

**Issue by JensKruger** [vanitasvitae/pgpainless#405]
We were attempting to use pgpainless with JDK 17 but encountered some issues.
SSL error: class "org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey" cannot be cast to class "java.security.interfaces.XECPublicKey."

In your commit history, I noticed that you switched from using "org.bouncycastle:bcprov-jdk15on/org.bouncycastle:bcpg-jdk15on" to "org.bouncycastle:bcprov-jdk15to18/org.bouncycastle:bcpg-jdk15to18" in 2022. According to the Bouncy Castle documentation, the new libraries are only compatible with Java 5-8, unlike the previous versions which were compatible with Java 5 and above.

Is pgpainless even intended to work with Java 17? I couldn't find any information about this in the readme.

**Comment by vanitasvitae** [comment]
Interesting finding, I wasn't aware that there are issues with JDK 17. Thanks for the report!

I will see if I can swap out the `-jdk15to18` variants for a more suitable artifact.

**Comment by vanitasvitae** [comment]
I think you should be fine manually excluding the `jdk15to18` variants of the Bouncycastle dependencies when adding PGPainless to your project. You can then manually depend on the `jdk18on` variants instead.

[Here](https://docs.gradle.org/current/userguide/resolution_rules.html#sec:module_replacement) are more information on how to do generic module substitution with gradle for example.

@DenBond7 @IvanPizhenko what is your opinion on switching BC to the `-jdk18on` variants? Do you see potential issues?

**Comment by JensKruger** [comment]
Thank you for replying so quickly. I will try to exclude it.

Just one more thing:
Do you remember why you switched from -jdk15on? My project already relies on -jdk15on, and I would rather continue using jdk15on instead of jdk18on. Can you recall any drawbacks of using jdk15on?

**Comment by vanitasvitae** [comment]
The reason is simply that the BC team discontinued `-jdk15on` in favor of `-jdk15to18` and `-jdk18on` sometime in 2022.

**Comment by DenBond7** [comment]
> @DenBond7 @IvanPizhenko what is your opinion on switching BC to the -jdk18on variants? Do you see potential issues?

Based on https://www.bouncycastle.org/latest_releases.html `The jdk18on jars are compiled to work with anything from Java 1.8 up.` In the Android project, we use [JavaVersion.VERSION_17](https://developer.android.com/build/jdks).

@vanitasvitae If you give me a hint on what I should change (or maybe create a branch with those changes) I will compile `jar` and run our tests to check if all things work well

**Comment by vanitasvitae** [comment]
If you could try the latest main branch (I already pushed a patch), that would already be enough to ensure that -jdk18on works just as well :)

**Comment by DenBond7** [comment]
> If you could try the latest main branch (I already pushed a patch), that would already be enough to ensure that -jdk18on works just as well :)

I didn't receive any issues. All works well ))

**Comment by vanitasvitae** [comment]
Perfect! Then the next release will depend on -jdk18on :)
Thanks everyone :)

**Comment by vanitasvitae** [comment]
I just released PGPainless 1.6.2 which should fix the issue :+1:
