### ISSUE TITLE
Detached Signature Verification

### ISSUE THREAD

**Issue by sushengloong** [vanitasvitae/pgpainless#407]
Hi, according to the [docs](https://pgpainless.readthedocs.io/en/latest/quickstart.html#id1), we can verify a detached signature as follows:-

```
List<Verification> verifications = sop.detachedVerify()
        .cert(signingCert)
        .signatures(detachedSignature)
        .data(signedMessage);
```

Does it mean that if `verifications` is not empty this is actually verified? Or do we still have to compare the fingerprint from the list (using `getSigningCertFingerprint()` / `getSigningKeyFingerprint()`) against the fingerprint of the `signingCert`?

**Comment by vanitasvitae** [comment]
The output will contain an entry for every signature that was successfully verified.
For a signature to be verified, the signers certificate must have been provided using `cert(...)`.

So if you only provide a single cert, and the output is not empty, then the entry will have been made by the single cert you provided.
If you provide multiple certs, you should inspect the result output to check, which cert was used to generate/verify the signature.

**Comment by sushengloong** [comment]
@vanitasvitae Thank you for your fast response and clear explanation!
