### ISSUE TITLE
Re-certify key user-id after it has been soft revoked - possible bug

### ISSUE THREAD

**Issue by Jerbell** [vanitasvitae/pgpainless#411]
Hi!

I'm doing a test case where the key UIDs are changed like:
```
Created with UIDs: [1@test.com]
Updated to: [1@test.com, 2@test.com] aka add <2@test.com>
Updated to: [2@test.com] aka remove <1@test.com> *Soft revoke*
Updated to [2@test.com, 1@test.com] aka add <1@test.com>
```
At this stage - the key only contains UID `2@test.com`. the add doesn't seem to work.
Can you confirm this behaviour - or am I doing something wrong?
If might be a bug with `SecretKeyRingEditorInterface addUserId(...)`

Thanks for investigating :)

EDIT: specifically I'm using the `SecretKeyRingEditorInterface addUserId(` and `SecretKeyRingEditorInterface removeUserId(` methods.

**Comment by vanitasvitae** [comment]
Does your test take the time dimension into consideration?

During evaluation, signatures are sorted by their creation time (which has a resolution of 1 second), so if two signatures have the same creation time, they can interfere in unwanted ways.

I have some tests in place which do similar things (although not exactly what you described, will add a test for that later), and those tests are a but flaky at times.
Not sure if this is caused by the test setup or by a faulty implementation though.

**Comment by Jerbell** [comment]
Cool - I'll try that with a delay & see what happens.

**Comment by Jerbell** [comment]
Ok - it's still failing, but I think it might be our problem now.  If you write your test like above let me know if it passes/fails. TIA :)

**Comment by Jerbell** [comment]
Ok - I've worked out what the problem is in our case.  If you `removeUserId` on a UID that is the primary UID then it remains the primary UID even if it's not in the UIDs.
I've fixed this on our end, though I wonder if perhaps it should be a library fix too? Up to you.
Thanks for your assistance.

**Comment by vanitasvitae** [comment]
Ah yeah, the fact that primary User-IDs are handled specially is a bit of a pain.
If the primary UserID is revoked, the whole certificate is invalidated, even if there are non-primary UserIDs left.

It is not easy to design the API such that there are no unwanted or unexpected side-effects.

In your case, you probably want to do the following:
```
Created with UIDs: [1@test.com (primary)]
Updated to: [1@test.com (primary), 2@test.com] aka add <2@test.com>
Updated to: [1@test.com, 2@test.com (primary)] aka setPrimary <2@test.com>
Updated to: [2@test.com (primary)] aka remove <1@test.com> *Soft revoke*
Updated to [2@test.com (primary), 1@test.com] aka add <1@test.com>
Optionally: Updated to [1@test.com (primary), 2@test.com] aka setPrimary <1@test.com>
```

This way you never end up with a certificate where the primary User ID is revoked.
Perhaps, to prevent side-effects you want to not mark UserIDs as primary, such that the latest UserID implicitly gets treated as primary?

**Comment by Jerbell** [comment]
Good idea. 
My solution is that if the primary UID is not the same as the old one, then I set it after any operation.  This covers the above scenario. 
Thanks for your help.
