### ISSUE TITLE
EncryptionOptions.addRecipient has an error

### ISSUE THREAD

**Issue by cpdw840624** [vanitasvitae/pgpainless#413]
PGPPublicKeyRing publicKey=PGPainless.readKeyRing().publicKeyRing(publicKeyIs);

           EncryptionStream encryptionStream = PGPainless.encryptAndOrSign()
                    .onOutputStream(outputStream)
                    .withOptions(ProducerOptions.signAndEncrypt(
                            new EncryptionOptions()
                                    .addRecipient(publicKey),

I use this code to enc data,but 
org.pgpainless.exception.KeyException$UnacceptableSelfSignatureException: Key B7183F5871E9536950FCE6ADA2674CADB65EBD45 does not have a valid/acceptable signature to derive an expiration date from.
	at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.java:287)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:252)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:240)
	at cn.com.goldwind.ercp.util.PgpUtils.encryptAndSignNab(PgpUtils.java:228)
	at cn.com.goldwind.ercp.util.PgpUtils.encryptAndSign_test(PgpUtils.java:553)
	at cn.com.goldwind.ercp.util.PgpUtils.main(PgpUtils.java:91)
Exception in thread "main" java.lang.NullPointerException
	at cn.com.goldwind.ercp.util.PgpUtils.encryptAndSign_test(PgpUtils.java:557)
	at cn.com.goldwind.ercp.util.PgpUtils.main(PgpUtils.java:91)

public key is 
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQENBFb8ae4BCAC/HBzOc4iSsr/uTAGqnkWQYw+Ov1Ps71Z+UkZWj7MZZaBhCbk4
WUxe9tlvxkhyusHYJRKTRXoSVYnN5XTlQUs0nE0PHAKjg9AfA+yXmktvt15wToPV
/qt6yktniFLUZHN+D5Z4PxG4a0bFK87jksxYX9M48NgAVyUZgwA969veCIqcu8Dy
Jjn20CinPNzI0DNSOMb6jyZgVV/BRtdJ3htiJVYplTpVSllLhlkfKvg8MsG0woCi
AolVHNNsnymxFaWAdRZuMkiYCd3k0SEc3apzyJWVqXWlQx0/xwfb+j42qzeKQQos
EfJWPOCMI9mzZxzY/5jieEx1H+pFHmvobOUhABEBAAG0P1RFU1QtRElSRUNUTElO
Sy10by1OQUIgPGl0LnNlY3VyaXR5LnBvbGljeS5zZXJ2aWNlc0BuYWIuY29tLmF1
PokBOAQTAQIAIgUCVvxp7gIbLwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQ
omdMrbZevUV0sggAmLWuvEqlhyVDRM8xlvuTEuJ7ZKIFm7iMgEEG2byGmC0GMDK7
m4fid7qB6/MXg3ht1CPXeoemzwMBJqyP/dhq0gEeTqfiLeKRQW3/UBkeUCEtJndd
H2//NQXpFGXkpBRSyid2DKl6PfjXs/JlBP9Id9OyAojQ3n9zvK/uA18jAvRagjkl
B0H2OdWyPajb30NHyOWp47yIkbG3cr1zzYJDjJbEAHAE9yoovSU8BcsyTeT/rzkx
CG0m3j9qREf83iowYTrpwcy1YXr1qKX4W4qSi3VP5RBrcoA+KrBvg8EL6qowDq6U
kXM9rn62ZyheRFY9+7Jin0f4djbVd/98JbKzDg==
=+2Lg
-----END PGP PUBLIC KEY BLOCK-----

**Comment by vanitasvitae** [comment]
PGPainless by default rejects signatures made using SHA1.
Your key appears to have a self-signature issued using SHA1 as hash algorithm.
To allow PGPainless to use the key, you need to modify its policy.
See [this example code](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/test/java/org/pgpainless/example/ManagePolicy.java#L67-L104) or take a look at [this page of the documentation](https://pgpainless.readthedocs.io/en/latest/quickstart.html#weak-keys-and-broken-algorithms) for more details.
