### ISSUE TITLE
How to add encryption subkey when it doesn't have one

### ISSUE THREAD

**Issue by Jerbell** [vanitasvitae/pgpainless#414]
This is possibly a noob question.

I have a private key. I can inspect it and see if it `isUsableForEncryption`.
I want to add an encryption subkey if it's not there.

I can see this method:
`public static SecretKeyRingEditorInterface modifyKeyRing(@Nonnull PGPSecretKeyRing secretKeys)`
which says you can add a subkey.

Could you please give me a hint on how to add a subkey to a `PGPSecretKeyRing`?

**Comment by vanitasvitae** [comment]
Of course :)

Take a look at [this example](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/test/java/org/pgpainless/example/ModifyKeys.java#L165-L171).
I would recommend using XDH on X25519 instead, and delegate `ENCRYPT_COMMS + ENCRYPT_STORAGE` to the key though.

So for you, the code would look like this:
```
        secretKey = PGPainless.modifyKeyRing(secretKey)
                .addSubKey(
                        KeySpec.getBuilder(KeyType.XDH(XDHSpec._X25519), KeyFlag.ENCRYPT_COMMS, KeyFlag.ENCRYPT_STORAGE)
                                .build(),
                        subkeyPassphrase,
                        protector)
                .done();
```

**Comment by Jerbell** [comment]
Those examples are great - I didn't realise.  Thanks so much Paul.

**Comment by Jerbell** [comment]
Sorry @vanitasvitae just a quick follow-up question: is it possible to generate a subkey based similar to the existing key? I'd need a new `KeyType` & then I could build another spec, though I don't see a simple way.
OR - would you recommend not doing that and just use XDH on X25519?
Thanks & feel free to close :)

**Comment by vanitasvitae** [comment]
Hey @Jerbell, sorry for the late response.

There is currently no comfortable method to chose a `KeyType` based on a given key.
I'm also not sure if it is possible/sensible to create such a method. Consider for example a key which only has an elliptic curve primary key using ECDSA and you want to add an encryption key. What algorithm should such a method choose? ECDH? XDH?

I'd argue, its up to the application developer (aka you ;P) to decide.

There is a number of `KeyType`s already predefined, those should cover everything you need.
For example, using `KeyType.RSA(RsaLength._4096)` you could specify the subkey to be a 4096 bit RSA key.

`KeyType.ECDSA` and `KeyType.EDDSA` are for signing/certification, while `KeyType.ECDH` and `KeyType.XDH` are for encryption. `KeyType.RSA` can be used for both and the other options aren't recommended.

For encryption I personally would recommend either XDH on X25519, or RSA with at least 3072 bits (better 4096).
For signing or certification I'd use EdDSA with Ed25519 or RSA.

Do you miss some specific algorithm?

**Comment by Jerbell** [comment]
Thanks for the explanation. My knowledge in this area is probably ~10%~ 5% of yours :)
We are actually matching `KeyType.XDH(XDHSpec._X25519)` with `KeyType.EDDSA(EdDSACurve._Ed25519)` in our UI code, so we are already doing something like this.
Thanks again!
