### ISSUE TITLE
PGPainless bombs out with signature tag 34

### ISSUE THREAD

**Issue by Jerbell** [vanitasvitae/pgpainless#418]
Using `gpg --full-generate-key` with GnuPG 2.4.3, sign key.

When we modify it later PGPainless `SignatureSubpacketTags` reads tag 34 which isn't supported and throws an exception.

Would be better if PGPainless gracefully dealt with this.

**Comment by sosnovsky** [comment]
> Using gpg --full-generate-key with GnuPG 2.4.3, sign key.

It also happens for me when I generate `ECC (sign and encrypt)` key (which is default option for GnuPG)

**Comment by vanitasvitae** [comment]
Hm, I'm trying to reproduce this issue right now.
I generated a fresh key and can confirm that it does contain the GnuPG AEAD preferences packet 34.
However, I played around with it for some time and I cannot reproduce a crash.

I'm on the main branch (which was rewritten in Kotlin recently), so the issue might no longer be there in my version.

What operation did you perform that causes PGPainless to throw an exception? Can you provide a minimal crashing example?

**Comment by Jerbell** [comment]
Hi, we were setting a new expiration - date. I'm just on my phone so can't check we're using the latest library but will do so in a few hours.

**Comment by vanitasvitae** [comment]
Got it. Could reproduce the issue, find the cause and write a patch :)

**Comment by vanitasvitae** [comment]
I just released PGPainless 1.6.4 which fixes the issue(s) you reported :)

**Comment by sosnovsky** [comment]
Wow, it was very quick, thanks @vanitasvitae !
I can confirm that issue is fixed now - expiration date is updated without any errors 👍
