### ISSUE TITLE
key cannot be used for encryption

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/pgpainless#421]
Hi, I noticed that a publicKey generated by gnuPG (2048, just default settings) without ExpirationDate set, cannot be used for encryption : 
```
        PGPainless
          .encryptAndOrSign()
          .onOutputStream(outputStream)
          .withOptions(
            ProducerOptions
              .encrypt(
                EncryptionOptions
                  .encryptCommunications()
                  .addRecipient(PGPainless.readKeyRing.publicKeyRing(publicKey))
                  .addPassphrase(Passphrase.fromPassword(passphrase))
              )
              .setAsciiArmor(true)
          )
```
Due to  : 
```
        Suppressed: org.pgpainless.exception.KeyException$UnacceptableSelfSignatureException: Key 28757F5AD7A4DDB70891C4AFE95E3C6299AAA603 does not have a valid/acceptable signature to derive an expiration date from.                       
                at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.java:298)                                                                                                                              
                at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:265)                                                                                                                                
                at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:253)                                                                                                                                
```

Is there a workaround of that?

_Originally posted by @pragmaxim in https://github.com/pgpainless/pgpainless/issues/14#issuecomment-1876697222_

**Comment by vanitasvitae** [comment]
Hey!
I suspect, that the key simply has a self-signature made using SHA-1, which is rejected by PGPainless with the default configuration.
To allow use of the key, please refer to the solution from https://github.com/pgpainless/pgpainless/issues/413

Feel free to re-open, if the issue is not resolved.

**Comment by pragmaxim** [comment]
Hi @vanitasvitae, thank you for clarifying. I went through the whole API but as this was not part of the builder pattern but rather static initialization, I missed that.

**Comment by vanitasvitae** [comment]
No problem, the error message is deceiving and could be improved, so you are not the first to miss that ;)

**Comment by pragmaxim** [comment]
The decryption part is also tricky, as if I use corresponding private key from gnuPG : 
```
        PGPainless
          .decryptAndOrVerify()
          .onInputStream(messageInputStream)
          .withOptions(new ConsumerOptions().addDecryptionKey(PGPainless.readKeyRing().secretKeyRing(privateKey)))
```
I get : 
```
[error]                         Suppressed: java.lang.NullPointerException: null
[error]                                 at org.bouncycastle.openpgp.PGPSecretKey.extractKeyData(Unknown Source)
[error]                                 at org.bouncycastle.openpgp.PGPSecretKey.extractPrivateKey(Unknown Source)
[error]                                 at org.pgpainless.key.protection.UnlockSecretKey.unlockSecretKey(UnlockSecretKey.java:40)
```

The final exception is : 
```
[error]         Suppressed: org.pgpainless.exception.WrongPassphraseException: Wrong passphrase provided for key xyz
[error]                 at org.pgpainless.key.protection.UnlockSecretKey.unlockSecretKey(UnlockSecretKey.java:42)                                                                                                                              
[error]                 at org.pgpainless.key.protection.UnlockSecretKey.unlockSecretKey(UnlockSecretKey.java:32)                                                                                                                              
[error]                 at org.pgpainless.decryption_verification.OpenPgpMessageInputStream.processEncryptedData(OpenPgpMessageInputStream.java:511)                                                                                           
```

But I don't pass any passhprase at encryption time and the private key is exported from gnuPG by : 
```
gpg --export-secret-key -a ID
```

**Comment by vanitasvitae** [comment]
Not at my computer right now, but I'd guess that the key is in fact encrypted, so you need to provide the passphrase. This can be done via the SecretKeyRingProtector class, which you then pass in along with the secret key.

**Comment by pragmaxim** [comment]
Ou my, yeah private key is always protected by the passphrase, sorry I got confused by it being passed when exporting the key :pray:

**Comment by vanitasvitae** [comment]
No worries :)
Have you checked out the documentation at https://pgpainless.readthedocs.io/ ?

Also, another shameless plug: https://openpgp.dev provides lots of background on the OpenPGP protocol, maybe you are interested (and even provide feedback 😉 )

**Comment by pragmaxim** [comment]
I've been deep down to it a lot, especially to Bouncy Castle :)) I got usually tricked by using common sense, ie. when I use passphrase to export secret protected by the same passphrase etc. :-D But these are relatively pleasant challenges.

Thank you for helping out so quickly and happy new year 2024 !
