### ISSUE TITLE
Key does not have a valid/acceptable signature to derive an expiration date from

### ISSUE THREAD

**Issue by elampros** [vanitasvitae/pgpainless#424]
I am facing an issue with a simple scenario. Sign and encrypt a zip file. I am trying this

```
SOP sop = new SOPImpl();
            byte[] ciphertext = sop.encrypt()
                    // encrypt for each recipient
                    .withCert(BOG_CERT.getBytes())
                    //.withCert(aliceCert)
                    // Optionally: Sign the message
                    .signWith(fKey.getBytes())
                    .withKeyPassword(passphrase) // if signing key is protected
                    // provide the plaintext
                    .plaintext(mytInputStream)
                    .getBytes();
```

and the code raised an exception: Key 762D0AC...FFE2A228D3CC6B does not have a valid/acceptable signature to derive an expiration date from.

However when I issue the command:
gpg bog_gr010_ccr_test_01.pub
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2022-11-16 [SC] [expires: 2024-11-15]
      762D0AC...FFE2A228D3CC6B
uid           XX010_XCR_TEST_01 (Test Key for XCR) <TechnicalSupport@treece.com>
sub   rsa4096 2022-11-16 [E] [expires: 2024-11-15]

Can you please help here?

```
<dependency>
			<groupId>org.pgpainless</groupId>
			<artifactId>pgpainless-core</artifactId>
			<version>1.6.1</version>
		</dependency>

		<dependency>
			<groupId>org.pgpainless</groupId>
			<artifactId>pgpainless-sop</artifactId>
			<version>1.6.1</version>
		</dependency>
```

**Comment by vanitasvitae** [comment]
Please check if your key carries a SHA-1 signature and adjust your policy accordingly: https://pgpainless.readthedocs.io/en/latest/quickstart.html#weak-keys-and-broken-algorithms

This is likely a duplicate of https://github.com/pgpainless/pgpainless/issues/398

**Comment by elampros** [comment]
Thank you very much, this seems to resolve my issue, therefore you can close it.
