### ISSUE TITLE
Support Java modules (JPMS)

### ISSUE THREAD

**Issue by craigraw** [vanitasvitae/pgpainless#428]
It is currently not possible to use pgpainless in a Java modular application. There are two problems:
1. The lack of `module-info.java` included in the jar, or even `Automatic-Module-Name` in the jar manifest. This is relatively easily solved.
2. The use of a split package for `org.bouncycastle` to implement `CachingBcPublicKeyDataDecryptorFactory`. It looks like this was done to get access to package-private `BcImplProvider`,  but it is a blocker for those who want to use this library in a modular application.

Although Java modules are not typically in high use on the server side, for a desktop client application (eg Swing or JavaFX) modules are crucial to get jlink/jpackage to produce nice small installers. From, say 100mb to ~30mb for a Hello World app.

**Comment by vanitasvitae** [comment]
Hey! Thanks for the bug report.
I haven't yet played around with modular applications at all, so it's good that you bring up these blockers.
I'll see how easy it is to fix the first point.

Regarding the second point, maybe it is worthwhile trying to get `CachingBcPublicKeyDataDecryptorFactory` upstreamed to BC?

**Comment by craigraw** [comment]
> Regarding the second point, maybe it is worthwhile trying to get CachingBcPublicKeyDataDecryptorFactory upstreamed to BC?

Yes, could be. Unfortunately it's not possible to have classes with the same package in two different jars with JPMS, so it will have to be moved out for support to be possible.

**Comment by vanitasvitae** [comment]
I guess its not even necessary to upstream the class as it can simply be moved to another package without losing its functionality.

I will move it for the next major release (which will take a while though).

**Comment by vanitasvitae** [comment]
Do you think https://github.com/pgpainless/pgpainless/pull/435 would together with #429 would fix your issue?

**Comment by craigraw** [comment]
From a quick review it looks like it would yes. Thanks!

**Comment by vanitasvitae** [comment]
Closed with PGPainless 1.6.7

**Comment by craigraw** [comment]
Thanks - I'm now using 1.6.7 and can confirm that basic modules support is working. Applications using jlink will need to set reads on `org.slf4j`, `org.bouncycastle.provider` and `org.bouncycastle.pg` as these modules are all required.
