### ISSUE TITLE
Please indicate support for the verification-only `sopv` subset

### ISSUE THREAD

**Issue by dkg** [vanitasvitae/pgpainless#445]
sop currently defines the [verification-only `sopv` subset](https://www.ietf.org/archive/id/draft-dkg-openpgp-stateless-cli-10.html#name-sopv-subset).  I believe that subset is fully supported by `pgpainless-cli`.  If that's the case, it would be great if `pgpainless-cli version --sopv` could emit `1.0\n' on stdout to formally announce support for it.

**Comment by vanitasvitae** [comment]
`sop-java` 10.0.0 already added support for this.
Once Debian can build Kotlin apps, we can bump pgpainless to support the new option :)

**Comment by vanitasvitae** [comment]
PGPainless 1.7 now comes with SOP 10 including support for `version --sopv` (though it does not provide a separate sopv binary).

**Comment by dkg** [comment]
thanks!

**Comment by dkg** [comment]
any chance we can backport this fix to the branch of `sop-java`  supported in debian?  i'd love for us to be able to mark pgpainless-cli as a valid alternative for `sopv`.

**Comment by vanitasvitae** [comment]
I'd like to keep the major version of the sop-java library to correspond to the revision of the spec it implements.
Also, given that `--sopv` was introduced in revision 10, I'd need to backport this feature not only to 7.X but also to 9.X (8.X is non-existent).
I can understand that you'd like to advance the usefulness of pgpainless in Debian, but I'd rather have the capability to package newer releases that use Kotlin (#439).

**Comment by dkg** [comment]
hm, if you're looking for the version of the spec, i think the draft number isn't the most useful value.  As noted in https://gitlab.com/dkg/openpgp-stateless-cli/-/merge_requests/36 it's not clear to me that the version number of the specification is a particularly helpful indicator.  I'd be up for thinking about how we do sensible versioning (maybe something like semver?) for the spec itself, but i don't think it's a great idea to tie software versioning to the spec version.

that said, i also definitely would prefer that debian can handle kotlin packaging, but that's pretty far outside of something i can make happen :(
