### ISSUE TITLE
some methods missing in Kotlin version of org.pgpainless.util.selection.userid.SelectUserId

### ISSUE THREAD

**Issue by agrahn** [vanitasvitae/pgpainless#449]
**Describe the bug**

After the library's rewrite in Kotlin, some of the methods formerly provided by the Java version are now missing:

- `selectUserIds`
- `firstMatch`

so that my project does not compile anymore.

Will these functions be ported to Kotlin too, or do I need to try this on my own?

**Version**

- `pgpainless-core`: 1.7.1

**Comment by vanitasvitae** [comment]
Hey, thanks for the report!
Use of `SelectUserId` is now deprecated. `selectUserIds` and `firstMatch` will not get ported, but should be easy enough to replicate :)

**Comment by agrahn** [comment]
> Hey, thanks for the report! Use of `SelectUserId` is now deprecated. `selectUserIds` and `firstMatch` will not get ported, but should be easy enough to replicate :)

Thanks for your reply.
 
So, the whole package `org.pgpainless.util.selection.userid` is already obsolete (`SelectUserId` is the only class it defines), despite `SelectUserId.kt` is new in 1.7.*?

What should be used instead?

**Comment by vanitasvitae** [comment]
Most places where `SelectUserId` is referenced already provide guidance on how to migrate away from it, e.g. https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/main/kotlin/org/pgpainless/key/modification/secretkeyring/SecretKeyRingEditor.kt#L150

Basically, you should use a Predicate instead, as that allows for more flexibility anyways :)
