### ISSUE TITLE
`UserId` email address is nullable?

### ISSUE THREAD

**Issue by Jerbell** [vanitasvitae/pgpainless#450]
**Describe the bug**
Hi - this is either a bug or I'm looking at the wrong RFC.
You have `UserId` `email` as `String?`, but I assume `UserId` is based on mailbox in RFC 5322 - or are you basing this on another RFC?
Would a PGP without an email address be of any use?

**Version**
- `pgpainless-core`: 1.7.1

**To Reproduce**
Use https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/main/kotlin/org/pgpainless/key/util/UserId.kt with null `email`

**Expected behavior**
I need the behaviour clarified.

**Additional context**
On a side note - your `emailPattern` looks exactly the same as the one I came up with. I don't remember helping you, so I'll say great minds think alike. :)

**Comment by vanitasvitae** [comment]
https://www.rfc-editor.org/rfc/rfc4880.html#section-5.11

> By convention, it
   includes an [RFC 2822](https://www.rfc-editor.org/rfc/rfc2822) [[RFC2822](https://www.rfc-editor.org/rfc/rfc2822)] mail name-addr, but there are no
   restrictions on its content.

**Comment by Jerbell** [comment]
I see. That's a little unhelpful (the spec that is).
Thanks very much!

**Comment by Jerbell** [comment]
Just to confirm @vanitasvitae - there's been no deliberate change here, just that you've converted to Kotlin?
Well done on the conversion. Kotlin is great.

**Comment by vanitasvitae** [comment]
Exactly :)

Thank you!
