### ISSUE TITLE
Behaviour changing for `lastModified` times

### ISSUE THREAD

**Issue by Jerbell** [vanitasvitae/pgpainless#451]
**Describe the bug**
I'm not sure if this is a bug or just need clarification.  I'm noticing that with when an equivalent key is inspected in 1.6.7 vs 1.7.1 then the `lastModified` date/time has changed. Is this expected behaviour for a reason - like something was fixed?

**Version**
- `pgpainless-core`: 1.7.1

**To Reproduce**
Here's a test key I use.
[wiktor-test.asc.txt](https://github.com/user-attachments/files/17484362/wiktor-test.asc.txt)
```java
    @Test
    public void pgpainlessLastModified() throws IOException {
        InputStream publicKey = this.getClass().getResource("wiktor-test.asc.txt").openStream();
        PGPPublicKeyRing keyRing = KeyRingReader.readPublicKeyRing(publicKey);
        KeyRingInfo info = PGPainless.inspectKeyRing(keyRing);
        System.out.println(info.getLastModified().toInstant());
    }
```
PGPainless 1.6.7: 2019-07-14T19:46:17Z
PGPainless 1.7.1: 2019-07-14T19:44:06Z

**Expected behavior**
Either the last modified time should be the same or there's a reason for it which isn't clear.

**Additional context**
Thanks for your help.

**Comment by sosnovsky** [comment]
I checked our test key with `openpgp.js` and looks like previous `pgppainless` version gave correct result as it returned time of the latest subkey signature creation, while newer version returns time of the key user `selfCertifications`:

1.7.1 uses this value
<img width="500" alt="Screenshot 2024-10-23 at 10 32 28" src="https://github.com/user-attachments/assets/1b767b77-342c-4c59-bca0-c6cdc99958c4">

1.6.7:
<img width="500" alt="Screenshot 2024-10-23 at 10 35 34" src="https://github.com/user-attachments/assets/d827b5c8-4012-4eaa-8912-2c2f3dc672ac">

Maybe this info will be helpful for finding original reason of such `lastModified` difference. Thanks for your help!

**Comment by vanitasvitae** [comment]
Thank you very much for the report!
There was indeed a mistake in the ported code. I fixed it with https://github.com/pgpainless/pgpainless/commit/f1610f64256828d7ba9190d73b20bd18d07b1ba1

The code accidentally returned the signature maxed by the key-rings creation date (a constant :P) instead of the signatures creation time.
Now the code behaves as before again :)

**Comment by sosnovsky** [comment]
Great, thanks for the fix!
