### ISSUE TITLE
pgpainless-cli extract-cert fails for revoked key

### ISSUE THREAD

**Issue by dkg** [vanitasvitae/pgpainless#452]
Running from debian testing:

```
0 dkg@bob:~$ pgpainless-cli version --extended
PGPainless-SOP 1.6.7
https://codeberg.org/PGPainless/pgpainless/src/branch/master/pgpainless-sop

Implementation of the Stateless OpenPGP Protocol Version 07
https://datatracker.ietf.org/doc/html/draft-dkg-openpgp-stateless-cli-07

Based on pgpainless-core 1.6.7
https://pgpainless.org

Using Bouncy Castle 1.77
https://www.bouncycastle.org/java.html
0 dkg@bob:~$ pgpainless-cli generate-key > tmp/test.key
0 dkg@bob:~$ pgpainless-cli revoke-key < tmp/test.key > tmp/test-revoked.key
0 dkg@bob:~$ pgpainless-cli extract-cert < tmp/test-revoked.key 
Standard Input appears not to contain a valid OpenPGP secret key.
41 dkg@bob:~$ 
```

But it's actually important that it's possible to extract a (revoked) certificate from a revoked secret key, so the failure of the final command is a problem.

Sorry that i haven't tested it against a more recent version, as i'm just using what's available in debian.   If it's already fixed in the more recent version, feel free to close it with the appropriate information.

**Comment by vanitasvitae** [comment]
Huh, thats a strange issue, I'll look into it. Thanks for reporting!

**Comment by vanitasvitae** [comment]
The output of `revoke-key` is already a public key (revocation certificate). Therefore, extracting a cert from a cert makes no sense.
Let me know, if you intended `revoke-key` to actually return the private key with a revocation signature added.

**Comment by dkg** [comment]
d'oh!  Embarrassing.  Yes, you're right, and `pgpainless-cli` was correct in this action.  Thanks for pushing this one back to me.
