### ISSUE TITLE
`pgpainless-cli version --extended` should report the version of `sop-java` that it is using

### ISSUE THREAD

**Issue by dkg** [vanitasvitae/pgpainless#454]
Over in #453, it looks like a bug fix didn't make it to me because the bug was fixed in sop-java, not in pgpainless-cli.

It would be nice if `pgpainless-cli version --extended` included  the version of sop-java in use as well.

**Comment by dkg** [comment]
maybe also report the versions of `picocli` and `sop-java-picocli``?

**Comment by vanitasvitae** [comment]
Hm. this is not a trivial thing to do. For PGPainless alone it took a workaround in the gradle [build script](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-cli/build.gradle#L17-L27) writing a properties file from which the VersionImpl class then [reads at runtime](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-sop/src/main/kotlin/org/pgpainless/sop/VersionImpl.kt#L48-L60).
I don't really like this solution, but its better than manually keeping some version string up to date.
I'm however not sure, how this would pan out for dynamic dependencies such as sop-java (even though pgpainless 1.6.8 should depend on sop-java 7.0.2, in debian it worked fine with 7.0.1 as you experienced).

**Comment by dkg** [comment]
yikes, i am definitely not trying to ask for any magic ponies.  i assumed that some form of module introspection was easily available at runtime, and that this would include the module version.  if it's a delicate or brittle process to do that in any reliable way, then that seems like an ecosystem issue, and probably not something to be fixed in pgpainless-cli itself.
