### ISSUE TITLE
Unable to remove UID from Secret key

### ISSUE THREAD

**Issue by Jerbell** [vanitasvitae/pgpainless#455]
**Describe the bug**
I'm trying to remove a uid from a secret key. I get this (shortened) stack trace:
```
java.util.NoSuchElementException: No matching user-ids found on the key.
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditor.revokeUserIds(SecretKeyRingEditor.kt:409)
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditor.revokeUserIds(SecretKeyRingEditor.kt:388)
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditor.removeUserId(SecretKeyRingEditor.kt:167)
	at org.pgpainless.key.modification.secretkeyring.SecretKeyRingEditor.removeUserId(SecretKeyRingEditor.kt:179)
```

**Version**
- `pgpainless-core`: 1.7.2 (might be present in 1.7.1 as well)

**To Reproduce**
```java
    @Test
    public void pgpainlessRemoveUid() throws IOException {
        SecretKeyRingProtector protector = new UnprotectedKeysProtector();
        InputStream publicKey = this.getClass().getResource("single_prv_key_armored.asc").openStream();
        PGPSecretKeyRing keyRing = KeyRingReader.readSecretKeyRing(publicKey);
        KeyRingInfo info = PGPainless.inspectKeyRing(keyRing);
        UserId uid = info.getValidAndExpiredUserIds().stream().map(UserId::onlyEmail).findFirst().get();
        System.out.println(uid);
        SecretKeyRingEditor editor = PGPainless.modifyKeyRing(keyRing);
        editor.removeUserId(uid, protector);
        editor.done();
    }
```

**Expected behavior**
I believe above should be ok?

**Additional context**
We have a similar test which worked ok for 1.6.7

**Comment by vanitasvitae** [comment]
My first instinct - only looking at your code - is, that the key contains user-id `Foo <bar@baz>` and you are mapping it to `bar@baz` (`map(UserID::onlyEmail)`, and then try to remove `bar@baz`, which will fail because the removal logic works on exact matches.

The reasoning behind exact matching is, that the key may contain multiple different UserIDs with the same email address. e.g. `Foo <bar@baz>`, `Foo Bar <bar@baz>`, `<bar@baz>`, so partial matching would not be sufficient.

**Comment by Jerbell** [comment]
I'm closing this. Instead of `replaceUid` we were doing an add & remove. Seems to work now 🤷

**Comment by Jerbell** [comment]
I think there might be something here... like if you create a key with a Uid containing a special character, and then try to remove it it will blow up. Want me to investigate further?
