### ISSUE TITLE
wrong decryption example in top-level README.md

### ISSUE THREAD

**Issue by agrahn** [vanitasvitae/pgpainless#456]
**Describe the bug**

The decryption example in the top-level README.md does not compile. The `addMessagePassphrase` method accepts only a single `Passphrase` object, rather than a `PGPSecretKeyRing[Collection]` and a `SecretKeyRingProtector`. It looks like `addDecryptionKeys` should be used here with the two given arguments. 

**Version**

- `pgpainless-core`: HEAD

**Comment by vanitasvitae** [comment]
Thanks for the report! Fixed :)
