### ISSUE TITLE
How to identify a key with Hash alg - SHA1(hash 2) in versions after 1.6.7

### ISSUE THREAD

**Issue by DenBond7** [vanitasvitae/pgpainless#461]
**Describe the bug**

I'm trying to migrate to `1.7.2`. In `1.6.7` we had worked default restrictions for using keys with `Hash alg - SHA1`.
I saw #448.

In `1.6.7` I didn't modify any Policy settings.
But after migration to `1.7.2` logic in our app was broken. Need to add that I've also tried the following code
```
PGPainless.getPolicy().dataSignatureHashAlgorithmPolicy =
        HashAlgorithmPolicy.static2022SignatureHashAlgorithmPolicy()

PGPainless.getPolicy().certificationSignatureHashAlgorithmPolicy =
        HashAlgorithmPolicy.static2022SignatureHashAlgorithmPolicy()
```

**Version**

- `pgpainless-core`: 1.7.2
- `pgpainless-sop`:

**To Reproduce**

I have a test key. It may be useful.

```
denbond7@WorkPC:~$ pgpdump 
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGdhoHoBDAC/Oen35S2i1JbpW/HpfqjjrqdX2b/WA3d+4chynnZBHIqUAq1Y
7oAm6AGAHxoF6/QdIh8mgZkOOibJ7Dw1mEwSHZq6Lw7xTc6yXd0VWbFdHE/LJi0r
sv8xKHmw8uPE5VV8vIZk2CTi/nrh2mLIQiN0DFFiLm0tlE1suOm2eb0D109JuU6M
UaVyJzDy1W4vgiBNM006U3o/COI7VFDGxZCjgO8MsXguoOn+PxgOCmAsNHInBi8p
ChibUzP3H4lt7DEDA171YD+mJkCTN6tRsIOIUG/4EDwG87NVQi9u5hGQOFK7XefY
uFcikxvz1pX+BZoUICfgfC6wSC10yfuUkQOlnOL25ejDODYJo6ivKnaaedpwyesu
SDe4fgS3G5A69TLt7o8SBgLSQm4pHCBCuAo4DUPp0hIKdYupQ7uUimCGocRoqh72
0I9CaYbuukmc0c0D+Z5ANL1zSFA46AJXDXFB5Q7thDQFer5xBkYyETwUmVnDOgHc
bfwkq5z7ixho9wsAEQEAAbQaVGVzdCA8c2hhMUBmbG93Y3J5cHQudGVzdD6JAc0E
EwECADgWIQTqd7YaYF1Fls2S9RFV46ESO7JHcwUCZ2GgegIbLwULCQgHAgYVCgkI
CwIEFgIDAQIeAQIXgAAKCRBV46ESO7JHc8mnC/YrxtFWaKoDI+OWHv49VceMUpiy
hIwTp47b/zCQgPnaegkvu0tQbWimYKNHk6XaHDVg7q7ozyXszi6xUe3MeLVLsiNk
I1SCBy58yy7U15guUk2fodbfkJIVy5XUhv0+lYc535v7rPt9FjAHZzOJh5abw936
S1BDgsh5mwoWcXV94EncPPqiGtoN5GIvaoiOAZNdUDpheo2rYv1A4sEigTt8XrTZ
/K9c51o/1SLtFHOZfyITUr/NaZN9Iq9gNR0gXAPRAU9rhr+govUIMeaNB8p9Jvkh
2TbL3Ha6PLdK68Oj3rk4lNT5Rqc2YHWOZjEvznNF7RAytgdS7zFSwPQZow9txqAc
UlLSjxnjuA9mYVURS6KI8Vzob0J+F2OKC7AhUP0lvTDErxCWbr40dEG2OjMdq5sj
39oUVQ42uRjfEl+JvP8zh/tMT8YXQ6xehnUpJ62C9RPa1WCqoOWGQLKjYYpZRrV0
PG0rJk5a6HI4KZywz/O/BaHvr6nJil5UE6E94Q==
=SGDQ
-----END PGP PUBLIC KEY BLOCK-----
Old: Public Key Packet(tag 6)(397 bytes)
	Ver 4 - new
	Public key creation time - Tue Dec 17 18:02:02 EET 2024
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(3072 bits) - ...
	RSA e(17 bits) - ...
Old: User ID Packet(tag 13)(26 bytes)
	User ID - Test <sha1@flowcrypt.test>
Old: Signature Packet(tag 2)(461 bytes)
	Ver 4 - new
	Sig type - Positive certification of a User ID and Public Key packet(0x13).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA1(hash 2)
	Hashed Sub: issuer fingerprint(sub 33)(21 bytes)
	 v4 -	Fingerprint - ea 77 b6 1a 60 5d 45 96 cd 92 f5 11 55 e3 a1 12 3b b2 47 73 
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Tue Dec 17 18:02:02 EET 2024
	Hashed Sub: key flags(sub 27)(1 bytes)
		Flag - This key may be used to certify other keys
		Flag - This key may be used to sign data
		Flag - This key may be used to encrypt communications
		Flag - This key may be used to encrypt storage
		Flag - This key may be used for authentication
	Hashed Sub: preferred symmetric algorithms(sub 11)(4 bytes)
		Sym alg - AES with 256-bit key(sym 9)
		Sym alg - AES with 192-bit key(sym 8)
		Sym alg - AES with 128-bit key(sym 7)
		Sym alg - Triple-DES(sym 2)
	Hashed Sub: preferred hash algorithms(sub 21)(5 bytes)
		Hash alg - SHA512(hash 10)
		Hash alg - SHA384(hash 9)
		Hash alg - SHA256(hash 8)
		Hash alg - SHA224(hash 11)
		Hash alg - SHA1(hash 2)
	Hashed Sub: preferred compression algorithms(sub 22)(3 bytes)
		Comp alg - ZLIB <RFC1950>(comp 2)
		Comp alg - BZip2(comp 3)
		Comp alg - ZIP <RFC1951>(comp 1)
	Hashed Sub: features(sub 30)(1 bytes)
		Flag - Modification detection (packets 18 and 19)
	Hashed Sub: key server preferences(sub 23)(1 bytes)
		Flag - No-modify
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x55E3A1123BB24773
	Hash left 2 bytes - c9 a7 
	RSA m^d mod n(3062 bits) - ...
		-> PKCS-1
```

**Expected behavior**

The main point is to know when a parsed key uses `Hash alg - SHA1(hash 2)` and disallow using the last one.

**Additional context**

I've also analyzed the source code. And it looks like now `PGPainless` doesn't throw `NoSuchElementException` 

https://github.com/pgpainless/pgpainless/blob/fdf49cfafbea21f1d6ae30c2de5f4b152e213e1e/pgpainless-core/src/main/kotlin/org/pgpainless/key/info/KeyRingInfo.kt#L174

In `1.6.7` we were getting an exception at this point when a user tried to import a key with `Hash alg - SHA1`

**Comment by vanitasvitae** [comment]
Hey!
In https://github.com/pgpainless/pgpainless/commit/620c1fc96a55c04d9607632b6967f66105681e55 I fixed a compatibility issue with keys that do not carry any self-certification signatures.

When you say, the change breaks your app, do you mean, that the key is still usable, although you expect it to not be?

**Comment by DenBond7** [comment]
Hi @vanitasvitae

> When you say, the change breaks your app, do you mean, that the key is still usable, although you expect it to not be?

Sorry, maybe I've used the wrong explanation. I meant that `dependabot` hasn't updated PGPainless automatically because some tests fail. After inspection, I've found that our app accepts keys with SHA1(1.7.2) but shouldn't(as was in 1.6.7). We allow SHA1 for the consumer version but disallow it for the enterprise(the last one has stronger restrictions).

So the question is, what is the correct way to detect parsed keys with SHA1 in `1.7.2` and prevent their use?

For example: 

1. I parse keys via `val pgpKeyRingCollection = PGPainless.readKeyRing().keyRingCollection(source, throwExceptionIfUnknownSource)`
2. after that I have some keys `val pgpKeyRingCollection.pgpSecretKeyRingCollection(pgpPublicKeyRingCollection)`
3. now I can use `val keyRingInfo = KeyRingInfo(pgpPKeyRing)`
4. Is it possible to have some method in `keyRingInfo` to detect a key with SHA1?

**Comment by vanitasvitae** [comment]
I see. I guess the best thing to do is probably to revert the commit that introduced the issue in the first place for 1.7.3.

This is a tricky one. PGPainless does not keep correct, but unacceptable signatures (such as SHA-1 sigs) in a dedicated place, so you would need to filter the PGPPublicKeyRing manually for self-signatures and check each one for its hash algorithm.

In pseudo-code, this would look something like
```
val primaryKey = pgpPublicKeyRing.getPublicKey()
val sha1DirectKeySelfSigs = primaryKey.getSignaturesOfType(PGPSignature.DIRECT_KEY)
        .filter(it -> it.issuerKeyId == primaryKey.keyId)
        .filter(it -> it.hashAlgorithm == HashAlgorithmTags.SHA1)
var hasSHA1Sigs = sha1DirectKeySelfSigs.isNotEmpty()

for (uid: String in primaryKey.userIds) {
    val sha1UIDSigs = primaryKey.getSignaturesForId(uid)
            .filter(it -> it.isCertification())
            .filter(it -> it.issuerKeyId == primaryKey.keyId)
            .filter(it -> it.hashAlgorithm == HashAlgorithmTags.SHA1)
    hasSHA1Sigs = hasSHA1Sigs | sha1UIDSigs.isNotEmpty()
}
```

**Comment by DenBond7** [comment]
> In pseudo-code, this would look something like

Looks good. I will try. Thanks a lot!

**Comment by DenBond7** [comment]
Hi @vanitasvitae. Thank you for your help. I've resolved my problem and we can close this issue.
